{-
   Veeva Vault API v25.1

   The latest GA version of the Vault REST API.

   OpenAPI Version: 3.0.0
   Veeva Vault API v25.1 API version: 1.0.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : VeevaVaultAPIV25.1.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module VeevaVaultAPIV25.1.Logging
  ( module VeevaVaultAPIV25.1.LoggingKatip
  ) where

import VeevaVaultAPIV25.1.LoggingKatip

#else

module VeevaVaultAPIV25.1.Logging
  ( module VeevaVaultAPIV25.1.LoggingMonadLogger
  ) where

import VeevaVaultAPIV25.1.LoggingMonadLogger

#endif
