{-
   Veeva Vault API v25.1

   The latest GA version of the Vault REST API.

   OpenAPI Version: 3.0.0
   Veeva Vault API v25.1 API version: 1.0.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : VeevaVaultAPIV25.1.Lens
-}

{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE RecordWildCards #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-matches -fno-warn-unused-binds -fno-warn-unused-imports #-}

module VeevaVaultAPIV25.1.ModelLens where

import qualified Data.Aeson as A
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Data, Typeable)
import qualified Data.Map as Map
import qualified Data.Set as Set
import qualified Data.Time as TI

import Data.Text (Text)

import Prelude (($), (.),(<$>),(<*>),(=<<),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

import VeevaVaultAPIV25.1.Model
import VeevaVaultAPIV25.1.Core


-- * VobjectsObjectNameActionsMergePostRequestInner

-- | 'vobjectsObjectNameActionsMergePostRequestInnerDuplicateRecordId' Lens
vobjectsObjectNameActionsMergePostRequestInnerDuplicateRecordIdL :: Lens_' VobjectsObjectNameActionsMergePostRequestInner (Maybe Text)
vobjectsObjectNameActionsMergePostRequestInnerDuplicateRecordIdL f VobjectsObjectNameActionsMergePostRequestInner{..} = (\vobjectsObjectNameActionsMergePostRequestInnerDuplicateRecordId -> VobjectsObjectNameActionsMergePostRequestInner { vobjectsObjectNameActionsMergePostRequestInnerDuplicateRecordId, ..} ) <$> f vobjectsObjectNameActionsMergePostRequestInnerDuplicateRecordId
{-# INLINE vobjectsObjectNameActionsMergePostRequestInnerDuplicateRecordIdL #-}

-- | 'vobjectsObjectNameActionsMergePostRequestInnerMainRecordId' Lens
vobjectsObjectNameActionsMergePostRequestInnerMainRecordIdL :: Lens_' VobjectsObjectNameActionsMergePostRequestInner (Maybe Text)
vobjectsObjectNameActionsMergePostRequestInnerMainRecordIdL f VobjectsObjectNameActionsMergePostRequestInner{..} = (\vobjectsObjectNameActionsMergePostRequestInnerMainRecordId -> VobjectsObjectNameActionsMergePostRequestInner { vobjectsObjectNameActionsMergePostRequestInnerMainRecordId, ..} ) <$> f vobjectsObjectNameActionsMergePostRequestInnerMainRecordId
{-# INLINE vobjectsObjectNameActionsMergePostRequestInnerMainRecordIdL #-}


