/*
 * Veeva Vault API v25.1
 *
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VobjectsObjectNameActionsMergePostRequestInner {
    #[serde(rename = "duplicate_record_id", skip_serializing_if = "Option::is_none")]
    pub duplicate_record_id: Option<String>,
    #[serde(rename = "main_record_id", skip_serializing_if = "Option::is_none")]
    pub main_record_id: Option<String>,
}

impl VobjectsObjectNameActionsMergePostRequestInner {
    pub fn new() -> VobjectsObjectNameActionsMergePostRequestInner {
        VobjectsObjectNameActionsMergePostRequestInner {
            duplicate_record_id: None,
            main_record_id: None,
        }
    }
}

