/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class VobjectsObjectNameActionsMergePostRequestInner {
    'duplicateRecordId'?: string;
    'mainRecordId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "duplicateRecordId",
            "baseName": "duplicate_record_id",
            "type": "string"
        },
        {
            "name": "mainRecordId",
            "baseName": "main_record_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return VobjectsObjectNameActionsMergePostRequestInner.attributeTypeMap;
    }
}

