/**
 * Veeva Vault API v25.1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VobjectsObjectNameActionsMergePostRequestInner { 
    duplicate_record_id?: string;
    main_record_id?: string;
}

