# coding: utf-8

"""
    Veeva Vault API v25.1

    The latest GA version of the Vault REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_api_get(self) -> None:
        """Test case for api_get

        Retrieve API Versions  # noqa: E501
        """
        pass

    def test_api_mdl_components_component_type_and_record_name_files_get(self) -> None:
        """Test case for api_mdl_components_component_type_and_record_name_files_get

        Retrieve Content File  # noqa: E501
        """
        pass

    def test_api_mdl_components_component_type_and_record_name_get(self) -> None:
        """Test case for api_mdl_components_component_type_and_record_name_get

        Retrieve Component Record (MDL)  # noqa: E501
        """
        pass

    def test_api_mdl_execute_async_job_id_results_get(self) -> None:
        """Test case for api_mdl_execute_async_job_id_results_get

        Retrieve Asynchronous MDL Script Results  # noqa: E501
        """
        pass

    def test_api_mdl_execute_async_post(self) -> None:
        """Test case for api_mdl_execute_async_post

        Execute MDL Script Asynchronously  # noqa: E501
        """
        pass

    def test_api_mdl_execute_post(self) -> None:
        """Test case for api_mdl_execute_post

        Execute MDL Script  # noqa: E501
        """
        pass

    def test_api_mdl_files_post(self) -> None:
        """Test case for api_mdl_files_post

        Upload Content File  # noqa: E501
        """
        pass

    def test_audittrail_audit_trail_type_get(self) -> None:
        """Test case for audittrail_audit_trail_type_get

        Retrieve Audit Details  # noqa: E501
        """
        pass

    def test_auth_discovery_post(self) -> None:
        """Test case for auth_discovery_post

        Authentication Type Discovery  # noqa: E501
        """
        pass

    def test_auth_oauth_session_oath_oidc_profile_id_post(self) -> None:
        """Test case for auth_oauth_session_oath_oidc_profile_id_post

        OAuth 2.0 / OpenID Connect  # noqa: E501
        """
        pass

    def test_auth_post(self) -> None:
        """Test case for auth_post

        User Name and Password  # noqa: E501
        """
        pass

    def test_code_class_name_delete(self) -> None:
        """Test case for code_class_name_delete

        Delete Single Source Code File  # noqa: E501
        """
        pass

    def test_code_class_name_disable_put(self) -> None:
        """Test case for code_class_name_disable_put

        Disable Vault Extension  # noqa: E501
        """
        pass

    def test_code_class_name_enable_put(self) -> None:
        """Test case for code_class_name_enable_put

        Enable Vault Extension  # noqa: E501
        """
        pass

    def test_code_class_name_get(self) -> None:
        """Test case for code_class_name_get

        Retrieve Single Source Code File  # noqa: E501
        """
        pass

    def test_code_profiler_get(self) -> None:
        """Test case for code_profiler_get

        Retrieve All Profiling Sessions  # noqa: E501
        """
        pass

    def test_code_profiler_post(self) -> None:
        """Test case for code_profiler_post

        Create Profiling Session  # noqa: E501
        """
        pass

    def test_code_profiler_session_name_actions_end_post(self) -> None:
        """Test case for code_profiler_session_name_actions_end_post

        End Profiling Session  # noqa: E501
        """
        pass

    def test_code_profiler_session_name_delete(self) -> None:
        """Test case for code_profiler_session_name_delete

        Delete Profiling Session  # noqa: E501
        """
        pass

    def test_code_profiler_session_name_get(self) -> None:
        """Test case for code_profiler_session_name_get

        Retrieve Profiling Session  # noqa: E501
        """
        pass

    def test_code_profiler_session_name_results_get(self) -> None:
        """Test case for code_profiler_session_name_results_get

        Download Profiling Session Results  # noqa: E501
        """
        pass

    def test_code_put(self) -> None:
        """Test case for code_put

        Add or Replace Single Source Code File  # noqa: E501
        """
        pass

    def test_composites_trees_edl_hierarchy_or_template_actions_listnodes_post(self) -> None:
        """Test case for composites_trees_edl_hierarchy_or_template_actions_listnodes_post

        Retrieve Specific Root Nodes  # noqa: E501
        """
        pass

    def test_composites_trees_edl_hierarchy_or_template_get(self) -> None:
        """Test case for composites_trees_edl_hierarchy_or_template_get

        Retrieve All Root Nodes  # noqa: E501
        """
        pass

    def test_composites_trees_edl_hierarchy_v_parent_node_id_children_get(self) -> None:
        """Test case for composites_trees_edl_hierarchy_v_parent_node_id_children_get

        Retrieve a Node's Children  # noqa: E501
        """
        pass

    def test_composites_trees_edl_hierarchy_v_parent_node_id_children_put(self) -> None:
        """Test case for composites_trees_edl_hierarchy_v_parent_node_id_children_put

        Update Node Order  # noqa: E501
        """
        pass

    def test_configuration_component_type_and_record_name_get(self) -> None:
        """Test case for configuration_component_type_and_record_name_get

        Retrieve Component Record (XML/JSON)  # noqa: E501
        """
        pass

    def test_configuration_component_type_get(self) -> None:
        """Test case for configuration_component_type_get

        Retrieve Component Record Collection  # noqa: E501
        """
        pass

    def test_configuration_object_name_and_object_type_get(self) -> None:
        """Test case for configuration_object_name_and_object_type_get

        Retrieve Details from a Specific Object  # noqa: E501
        """
        pass

    def test_configuration_objecttype_get(self) -> None:
        """Test case for configuration_objecttype_get

        Retrieve Details from All Object Types  # noqa: E501
        """
        pass

    def test_configuration_role_assignment_rule_delete(self) -> None:
        """Test case for configuration_role_assignment_rule_delete

        Delete Lifecycle Role Assignment Override Rules  # noqa: E501
        """
        pass

    def test_configuration_role_assignment_rule_get(self) -> None:
        """Test case for configuration_role_assignment_rule_get

        Retrieve Lifecycle Role Assignment Rules (Default & Override)  # noqa: E501
        """
        pass

    def test_configuration_role_assignment_rule_post(self) -> None:
        """Test case for configuration_role_assignment_rule_post

        Create Lifecycle Role Assignment Override Rules  # noqa: E501
        """
        pass

    def test_configuration_role_assignment_rule_put(self) -> None:
        """Test case for configuration_role_assignment_rule_put

        Update Lifecycle Role Assignment Rules (Default & Override)  # noqa: E501
        """
        pass

    def test_delegation_login_post(self) -> None:
        """Test case for delegation_login_post

        Initiate Delegated Session  # noqa: E501
        """
        pass

    def test_delegation_vaults_get(self) -> None:
        """Test case for delegation_vaults_get

        Retrieve Delegations  # noqa: E501
        """
        pass

    def test_keep_alive_post(self) -> None:
        """Test case for keep_alive_post

        Session Keep Alive  # noqa: E501
        """
        pass

    def test_limits_get(self) -> None:
        """Test case for limits_get

        Retrieve Limits on Objects  # noqa: E501
        """
        pass

    def test_logs_api_usage_get(self) -> None:
        """Test case for logs_api_usage_get

        Download Daily API Usage  # noqa: E501
        """
        pass

    def test_logs_code_debug_get(self) -> None:
        """Test case for logs_code_debug_get

        Retrieve All Debug Logs  # noqa: E501
        """
        pass

    def test_logs_code_debug_id_actions_reset_delete(self) -> None:
        """Test case for logs_code_debug_id_actions_reset_delete

        Delete Debug Log  # noqa: E501
        """
        pass

    def test_logs_code_debug_id_actions_reset_post(self) -> None:
        """Test case for logs_code_debug_id_actions_reset_post

        Reset Debug Log  # noqa: E501
        """
        pass

    def test_logs_code_debug_id_files_get(self) -> None:
        """Test case for logs_code_debug_id_files_get

        Download Debug Log Files  # noqa: E501
        """
        pass

    def test_logs_code_debug_id_get(self) -> None:
        """Test case for logs_code_debug_id_get

        Retrieve Single Debug Log  # noqa: E501
        """
        pass

    def test_logs_code_debug_post(self) -> None:
        """Test case for logs_code_debug_post

        Create Debug Log  # noqa: E501
        """
        pass

    def test_logs_code_runtime_get(self) -> None:
        """Test case for logs_code_runtime_get

        Download SDK Runtime Log  # noqa: E501
        """
        pass

    def test_messages_message_type_actions_import_post(self) -> None:
        """Test case for messages_message_type_actions_import_post

        Import Bulk Translation File  # noqa: E501
        """
        pass

    def test_messages_message_type_language_lang_actions_export_post(self) -> None:
        """Test case for messages_message_type_language_lang_actions_export_post

        Export Bulk Translation File  # noqa: E501
        """
        pass

    def test_metadata_audittrail_audit_trail_type_get(self) -> None:
        """Test case for metadata_audittrail_audit_trail_type_get

        Retrieve Audit Metadata  # noqa: E501
        """
        pass

    def test_metadata_audittrail_get(self) -> None:
        """Test case for metadata_audittrail_get

        Retrieve Audit Types  # noqa: E501
        """
        pass

    def test_metadata_components_component_type_get(self) -> None:
        """Test case for metadata_components_component_type_get

        Retrieve Component Type Metadata  # noqa: E501
        """
        pass

    def test_metadata_components_get(self) -> None:
        """Test case for metadata_components_get

        Retrieve All Component Metadata  # noqa: E501
        """
        pass

    def test_metadata_objects_binders_templates_bindernodes_get(self) -> None:
        """Test case for metadata_objects_binders_templates_bindernodes_get

        Retrieve Binder Template Node Metadata  # noqa: E501
        """
        pass

    def test_metadata_objects_binders_templates_get(self) -> None:
        """Test case for metadata_objects_binders_templates_get

        Retrieve Binder Template Metadata  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_annotations_placemarks_types_placemark_type_get(self) -> None:
        """Test case for metadata_objects_documents_annotations_placemarks_types_placemark_type_get

        Retrieve Annotation Placemark Type Metadata  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_annotations_references_types_reference_type_get(self) -> None:
        """Test case for metadata_objects_documents_annotations_references_types_reference_type_get

        Retrieve Annotation Reference Type Metadata  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_annotations_types_annotation_type_get(self) -> None:
        """Test case for metadata_objects_documents_annotations_types_annotation_type_get

        Retrieve Annotation Type Metadata  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_events_event_type_types_event_subtype_get(self) -> None:
        """Test case for metadata_objects_documents_events_event_type_types_event_subtype_get

        Retrieve Document Event SubType Metadata  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_events_get(self) -> None:
        """Test case for metadata_objects_documents_events_get

        Retrieve Document Event Types and Subtypes  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_lock_get(self) -> None:
        """Test case for metadata_objects_documents_lock_get

        Retrieve Document Lock Metadata  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_properties_find_common_post(self) -> None:
        """Test case for metadata_objects_documents_properties_find_common_post

        Retrieve Common Document Fields  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_properties_get(self) -> None:
        """Test case for metadata_objects_documents_properties_get

        Retrieve All Document Fields  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_templates_get(self) -> None:
        """Test case for metadata_objects_documents_templates_get

        Retrieve Document Template Metadata  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_types_get(self) -> None:
        """Test case for metadata_objects_documents_types_get

        Retrieve All Document Types  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_types_type_get(self) -> None:
        """Test case for metadata_objects_documents_types_type_get

        Retrieve Document Type  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_types_type_relationships_get(self) -> None:
        """Test case for metadata_objects_documents_types_type_relationships_get

        Retrieve Document Type Relationships  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_types_type_subtypes_subtype_classifications_classification_get(self) -> None:
        """Test case for metadata_objects_documents_types_type_subtypes_subtype_classifications_classification_get

        Retrieve Document Classification  # noqa: E501
        """
        pass

    def test_metadata_objects_documents_types_type_subtypes_subtype_get(self) -> None:
        """Test case for metadata_objects_documents_types_type_subtypes_subtype_get

        Retrieve Document Subtype  # noqa: E501
        """
        pass

    def test_metadata_objects_groups_get(self) -> None:
        """Test case for metadata_objects_groups_get

        Retrieve Group Metadata  # noqa: E501
        """
        pass

    def test_metadata_objects_securitypolicies_get(self) -> None:
        """Test case for metadata_objects_securitypolicies_get

        Retrieve Security Policy Metadata  # noqa: E501
        """
        pass

    def test_metadata_objects_users_get(self) -> None:
        """Test case for metadata_objects_users_get

        Retrieve User Metadata  # noqa: E501
        """
        pass

    def test_metadata_query_archived_documents_relationships_document_signature_sysr_get(self) -> None:
        """Test case for metadata_query_archived_documents_relationships_document_signature_sysr_get

        Retrieve Archived Document Signature Metadata  # noqa: E501
        """
        pass

    def test_metadata_query_documents_relationships_document_signature_sysr_get(self) -> None:
        """Test case for metadata_query_documents_relationships_document_signature_sysr_get

        Retrieve Document Signature Metadata  # noqa: E501
        """
        pass

    def test_metadata_vobjects_get(self) -> None:
        """Test case for metadata_vobjects_get

        Retrieve Object Collection  # noqa: E501
        """
        pass

    def test_metadata_vobjects_object_name_actions_canceldeployment_post(self) -> None:
        """Test case for metadata_vobjects_object_name_actions_canceldeployment_post

        Cancel Raw Object Deployment  # noqa: E501
        """
        pass

    def test_metadata_vobjects_object_name_fields_object_field_name_get(self) -> None:
        """Test case for metadata_vobjects_object_name_fields_object_field_name_get

        Retrieve Object Field Metadata  # noqa: E501
        """
        pass

    def test_metadata_vobjects_object_name_get(self) -> None:
        """Test case for metadata_vobjects_object_name_get

        Retrieve Object Metadata  # noqa: E501
        """
        pass

    def test_metadata_vobjects_object_name_page_layouts_get(self) -> None:
        """Test case for metadata_vobjects_object_name_page_layouts_get

        Retrieve Page Layouts  # noqa: E501
        """
        pass

    def test_metadata_vobjects_object_name_page_layouts_layout_name_get(self) -> None:
        """Test case for metadata_vobjects_object_name_page_layouts_layout_name_get

        Retrieve Page Layout Metadata  # noqa: E501
        """
        pass

    def test_notifications_histories_get(self) -> None:
        """Test case for notifications_histories_get

        Retrieve Email Notification Histories  # noqa: E501
        """
        pass

    def test_object_workflow_actions_action_get(self) -> None:
        """Test case for object_workflow_actions_action_get

        Retrieve Bulk Workflow Action Details  # noqa: E501
        """
        pass

    def test_object_workflow_actions_action_post(self) -> None:
        """Test case for object_workflow_actions_action_post

        Initiate Workflow Actions on Multiple Workflows  # noqa: E501
        """
        pass

    def test_object_workflow_actions_canceltasks_post(self) -> None:
        """Test case for object_workflow_actions_canceltasks_post

        Cancel Workflow Tasks  # noqa: E501
        """
        pass

    def test_object_workflow_actions_cancelworkflows_post(self) -> None:
        """Test case for object_workflow_actions_cancelworkflows_post

        Cancel Workflows  # noqa: E501
        """
        pass

    def test_object_workflow_actions_get(self) -> None:
        """Test case for object_workflow_actions_get

        Retrieve Bulk Workflow Actions  # noqa: E501
        """
        pass

    def test_object_workflow_actions_reassigntasks_post(self) -> None:
        """Test case for object_workflow_actions_reassigntasks_post

        Reassign Workflow Tasks  # noqa: E501
        """
        pass

    def test_object_workflow_actions_replaceworkflowowner_post(self) -> None:
        """Test case for object_workflow_actions_replaceworkflowowner_post

        Replace Workflow Owner  # noqa: E501
        """
        pass

    def test_objects_binders_actions_export_job_id_results_get(self) -> None:
        """Test case for objects_binders_actions_export_job_id_results_get

        Retrieve Binder Export Results  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_actions_export_post(self) -> None:
        """Test case for objects_binders_binder_id_actions_export_post

        Export Binder (Latest Version)  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_actions_post(self) -> None:
        """Test case for objects_binders_binder_id_actions_post

        Refresh Binder Auto-Filing  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_binding_rule_put(self) -> None:
        """Test case for objects_binders_binder_id_binding_rule_put

        Update Binding Rule  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_delete(self) -> None:
        """Test case for objects_binders_binder_id_delete

        Delete Binder  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_documents_node_id_binding_rule_put(self) -> None:
        """Test case for objects_binders_binder_id_documents_node_id_binding_rule_put

        Update Binder Document Binding Rule  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_documents_post(self) -> None:
        """Test case for objects_binders_binder_id_documents_post

        Add Document to Binder  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_documents_section_id_delete(self) -> None:
        """Test case for objects_binders_binder_id_documents_section_id_delete

        Remove Document from Binder  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_documents_section_id_put(self) -> None:
        """Test case for objects_binders_binder_id_documents_section_id_put

        Move Document in Binder  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_get(self) -> None:
        """Test case for objects_binders_binder_id_get

        Retrieve Binder  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_post(self) -> None:
        """Test case for objects_binders_binder_id_post

        Create Binder Version  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_put(self) -> None:
        """Test case for objects_binders_binder_id_put

        Update Binder  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_roles_role_name_and_user_or_group_id_delete(self) -> None:
        """Test case for objects_binders_binder_id_roles_role_name_and_user_or_group_id_delete

        Remove Users & Groups from Roles on a Single Binder  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_sections_node_id_binding_rule_put(self) -> None:
        """Test case for objects_binders_binder_id_sections_node_id_binding_rule_put

        Update Binder Section Binding Rule  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_sections_node_id_put(self) -> None:
        """Test case for objects_binders_binder_id_sections_node_id_put

        Update Binder Section  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_sections_post(self) -> None:
        """Test case for objects_binders_binder_id_sections_post

        Create Binder Section  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_sections_section_id_delete(self) -> None:
        """Test case for objects_binders_binder_id_sections_section_id_delete

        Delete Binder Section  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_sections_section_id_get(self) -> None:
        """Test case for objects_binders_binder_id_sections_section_id_get

        Retrieve Binder Sections  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_versions_get(self) -> None:
        """Test case for objects_binders_binder_id_versions_get

        Retrieve All Binder Versions  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_versions_major_version_minor_version_actions_export_post(self) -> None:
        """Test case for objects_binders_binder_id_versions_major_version_minor_version_actions_export_post

        Export Binder (Specific Version)  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_versions_major_version_minor_version_delete(self) -> None:
        """Test case for objects_binders_binder_id_versions_major_version_minor_version_delete

        Delete Binder Version  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_versions_major_version_minor_version_get(self) -> None:
        """Test case for objects_binders_binder_id_versions_major_version_minor_version_get

        Retrieve Binder Version  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_versions_major_version_minor_version_put(self) -> None:
        """Test case for objects_binders_binder_id_versions_major_version_minor_version_put

        Update Binder Version  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_versions_major_version_minor_version_relationships_post(self) -> None:
        """Test case for objects_binders_binder_id_versions_major_version_minor_version_relationships_post

        Create Binder Relationship  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_versions_major_version_minor_version_relationships_relationship_id_delete(self) -> None:
        """Test case for objects_binders_binder_id_versions_major_version_minor_version_relationships_relationship_id_delete

        Delete Binder Relationship  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_versions_major_version_minor_version_relationships_relationship_id_get(self) -> None:
        """Test case for objects_binders_binder_id_versions_major_version_minor_version_relationships_relationship_id_get

        Retrieve Binder Relationship  # noqa: E501
        """
        pass

    def test_objects_binders_binder_id_versions_major_version_minor_version_sections_section_id_get(self) -> None:
        """Test case for objects_binders_binder_id_versions_major_version_minor_version_sections_section_id_get

        Retrieve Binder Version Section  # noqa: E501
        """
        pass

    def test_objects_binders_id_roles_get(self) -> None:
        """Test case for objects_binders_id_roles_get

        Retrieve All Binder Roles  # noqa: E501
        """
        pass

    def test_objects_binders_id_roles_post(self) -> None:
        """Test case for objects_binders_id_roles_post

        Assign Users & Groups to Roles on a Single Binder  # noqa: E501
        """
        pass

    def test_objects_binders_id_roles_role_name_get(self) -> None:
        """Test case for objects_binders_id_roles_role_name_get

        Retrieve Document Role  # noqa: E501
        """
        pass

    def test_objects_binders_id_versions_major_version_minor_version_lifecycle_actions_get(self) -> None:
        """Test case for objects_binders_id_versions_major_version_minor_version_lifecycle_actions_get

        Retrieve Binder User Actions  # noqa: E501
        """
        pass

    def test_objects_binders_id_versions_major_version_minor_version_lifecycle_actions_name_v_entry_requirements_get(self) -> None:
        """Test case for objects_binders_id_versions_major_version_minor_version_lifecycle_actions_name_v_entry_requirements_get

        Retrieve Binder Entry Criteria  # noqa: E501
        """
        pass

    def test_objects_binders_id_versions_major_version_minor_version_lifecycle_actions_name_v_put(self) -> None:
        """Test case for objects_binders_id_versions_major_version_minor_version_lifecycle_actions_name_v_put

        Initiate Binder User Action  # noqa: E501
        """
        pass

    def test_objects_binders_lifecycle_actions_post(self) -> None:
        """Test case for objects_binders_lifecycle_actions_post

        Retrieve User Actions on Multiple Binders  # noqa: E501
        """
        pass

    def test_objects_binders_lifecycle_actions_user_action_name_put(self) -> None:
        """Test case for objects_binders_lifecycle_actions_user_action_name_put

        Initiate Bulk Binder User Actions  # noqa: E501
        """
        pass

    def test_objects_binders_post(self) -> None:
        """Test case for objects_binders_post

        Create Binder  # noqa: E501
        """
        pass

    def test_objects_binders_templates_get(self) -> None:
        """Test case for objects_binders_templates_get

        Retrieve Binder Template Collection  # noqa: E501
        """
        pass

    def test_objects_binders_templates_post(self) -> None:
        """Test case for objects_binders_templates_post

        Create Binder Template  # noqa: E501
        """
        pass

    def test_objects_binders_templates_put(self) -> None:
        """Test case for objects_binders_templates_put

        Update Binder Template  # noqa: E501
        """
        pass

    def test_objects_binders_templates_template_name_bindernodes_get(self) -> None:
        """Test case for objects_binders_templates_template_name_bindernodes_get

        Retrieve Binder Template Node Attributes  # noqa: E501
        """
        pass

    def test_objects_binders_templates_template_name_bindernodes_post(self) -> None:
        """Test case for objects_binders_templates_template_name_bindernodes_post

        Create Binder Template Node  # noqa: E501
        """
        pass

    def test_objects_binders_templates_template_name_bindernodes_put(self) -> None:
        """Test case for objects_binders_templates_template_name_bindernodes_put

        Replace Binder Template Nodes  # noqa: E501
        """
        pass

    def test_objects_binders_templates_template_name_delete(self) -> None:
        """Test case for objects_binders_templates_template_name_delete

        Delete Binder Template  # noqa: E501
        """
        pass

    def test_objects_binders_templates_template_name_get(self) -> None:
        """Test case for objects_binders_templates_template_name_get

        Retrieve Binder Template Attributes  # noqa: E501
        """
        pass

    def test_objects_deletions_documents_get(self) -> None:
        """Test case for objects_deletions_documents_get

        Retrieve Deleted Document IDs  # noqa: E501
        """
        pass

    def test_objects_deletions_vobjects_object_name_get(self) -> None:
        """Test case for objects_deletions_vobjects_object_name_get

        Retrieve Deleted Object Record ID  # noqa: E501
        """
        pass

    def test_objects_documents_actions_get(self) -> None:
        """Test case for objects_documents_actions_get

        Retrieve All Document Workflows  # noqa: E501
        """
        pass

    def test_objects_documents_actions_lifecycle_and_state_and_action_job_id_results_get(self) -> None:
        """Test case for objects_documents_actions_lifecycle_and_state_and_action_job_id_results_get

        Download Controlled Copy Job Results  # noqa: E501
        """
        pass

    def test_objects_documents_actions_workflow_name_get(self) -> None:
        """Test case for objects_documents_actions_workflow_name_get

        Retrieve Document Workflow Details  # noqa: E501
        """
        pass

    def test_objects_documents_actions_workflow_name_post(self) -> None:
        """Test case for objects_documents_actions_workflow_name_post

        Initiate Document Workflow  # noqa: E501
        """
        pass

    def test_objects_documents_annotations_batch_delete(self) -> None:
        """Test case for objects_documents_annotations_batch_delete

        Delete Annotations  # noqa: E501
        """
        pass

    def test_objects_documents_annotations_batch_post(self) -> None:
        """Test case for objects_documents_annotations_batch_post

        Create Multiple Annotations  # noqa: E501
        """
        pass

    def test_objects_documents_annotations_batch_put(self) -> None:
        """Test case for objects_documents_annotations_batch_put

        Update Annotations  # noqa: E501
        """
        pass

    def test_objects_documents_annotations_replies_batch_post(self) -> None:
        """Test case for objects_documents_annotations_replies_batch_post

        Add Annotation Replies  # noqa: E501
        """
        pass

    def test_objects_documents_attachments_batch_delete(self) -> None:
        """Test case for objects_documents_attachments_batch_delete

        Delete Multiple Document Attachments  # noqa: E501
        """
        pass

    def test_objects_documents_attachments_batch_post(self) -> None:
        """Test case for objects_documents_attachments_batch_post

        Create Multiple Document Attachments  # noqa: E501
        """
        pass

    def test_objects_documents_attachments_batch_put(self) -> None:
        """Test case for objects_documents_attachments_batch_put

        Update Multiple Document Attachment Descriptions  # noqa: E501
        """
        pass

    def test_objects_documents_batch_actions_fileextract_job_id_results_get(self) -> None:
        """Test case for objects_documents_batch_actions_fileextract_job_id_results_get

        Retrieve Document Export Results  # noqa: E501
        """
        pass

    def test_objects_documents_batch_actions_fileextract_post(self) -> None:
        """Test case for objects_documents_batch_actions_fileextract_post

        Export Documents  # noqa: E501
        """
        pass

    def test_objects_documents_batch_actions_reclassify_put(self) -> None:
        """Test case for objects_documents_batch_actions_reclassify_put

        Reclassify Multiple Documents  # noqa: E501
        """
        pass

    def test_objects_documents_batch_actions_rerender_post(self) -> None:
        """Test case for objects_documents_batch_actions_rerender_post

        Update Multiple Document Renditions  # noqa: E501
        """
        pass

    def test_objects_documents_batch_delete(self) -> None:
        """Test case for objects_documents_batch_delete

        Delete Multiple Documents  # noqa: E501
        """
        pass

    def test_objects_documents_batch_lock_delete(self) -> None:
        """Test case for objects_documents_batch_lock_delete

        Undo Collaborative Authoring Checkout  # noqa: E501
        """
        pass

    def test_objects_documents_batch_post(self) -> None:
        """Test case for objects_documents_batch_post

        Create Multiple Documents  # noqa: E501
        """
        pass

    def test_objects_documents_batch_put(self) -> None:
        """Test case for objects_documents_batch_put

        Update Multiple Documents  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_anchors_get(self) -> None:
        """Test case for objects_documents_doc_id_anchors_get

        Retrieve Anchor IDs  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_annotations_file_get(self) -> None:
        """Test case for objects_documents_doc_id_annotations_file_get

        Export Document Annotations to PDF  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_annotations_file_post(self) -> None:
        """Test case for objects_documents_doc_id_annotations_file_post

        Import Document Annotations from PDF  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_attachments_attachment_id_delete(self) -> None:
        """Test case for objects_documents_doc_id_attachments_attachment_id_delete

        Delete Single Document Attachment  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_attachments_attachment_id_file_get(self) -> None:
        """Test case for objects_documents_doc_id_attachments_attachment_id_file_get

        Download Document Attachment  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_attachments_attachment_id_get(self) -> None:
        """Test case for objects_documents_doc_id_attachments_attachment_id_get

        Retrieve Document Attachment Metadata  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_attachments_attachment_id_put(self) -> None:
        """Test case for objects_documents_doc_id_attachments_attachment_id_put

        Update Document Attachment Description  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_attachments_attachment_id_versions_attachment_version_delete(self) -> None:
        """Test case for objects_documents_doc_id_attachments_attachment_id_versions_attachment_version_delete

        Delete Single Document Attachment Version  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_attachments_attachment_id_versions_attachment_version_file_get(self) -> None:
        """Test case for objects_documents_doc_id_attachments_attachment_id_versions_attachment_version_file_get

        Download Document Attachment Version  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_attachments_attachment_id_versions_attachment_version_get(self) -> None:
        """Test case for objects_documents_doc_id_attachments_attachment_id_versions_attachment_version_get

        Retrieve Document Attachment Version Metadata  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_attachments_attachment_id_versions_attachment_version_post(self) -> None:
        """Test case for objects_documents_doc_id_attachments_attachment_id_versions_attachment_version_post

        Restore Document Attachment Version  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_attachments_attachment_id_versions_get(self) -> None:
        """Test case for objects_documents_doc_id_attachments_attachment_id_versions_get

        Retrieve Document Attachment Versions  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_attachments_file_get(self) -> None:
        """Test case for objects_documents_doc_id_attachments_file_get

        Download All Document Attachments  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_attachments_get(self) -> None:
        """Test case for objects_documents_doc_id_attachments_get

        Retrieve Document Attachments  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_attachments_post(self) -> None:
        """Test case for objects_documents_doc_id_attachments_post

        Create Document Attachment  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_audittrail_get(self) -> None:
        """Test case for objects_documents_doc_id_audittrail_get

        Retrieve Complete Audit History for a Single Document  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_delete(self) -> None:
        """Test case for objects_documents_doc_id_delete

        Delete Single Document  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_events_get(self) -> None:
        """Test case for objects_documents_doc_id_events_get

        Retrieve Document Events  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_file_get(self) -> None:
        """Test case for objects_documents_doc_id_file_get

        Download Document File  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_get(self) -> None:
        """Test case for objects_documents_doc_id_get

        Retrieve Document  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_lock_delete(self) -> None:
        """Test case for objects_documents_doc_id_lock_delete

        Delete Document Lock  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_lock_get(self) -> None:
        """Test case for objects_documents_doc_id_lock_get

        Retrieve Document Lock  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_lock_post(self) -> None:
        """Test case for objects_documents_doc_id_lock_post

        Create Document Lock  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_major_version_minor_version_attachments_file_get(self) -> None:
        """Test case for objects_documents_doc_id_major_version_minor_version_attachments_file_get

        Download All Document Version Attachments  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_post(self) -> None:
        """Test case for objects_documents_doc_id_post

        Create Single Document Version  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_put(self) -> None:
        """Test case for objects_documents_doc_id_put

        Update Single Document  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_renditions_get(self) -> None:
        """Test case for objects_documents_doc_id_renditions_get

        Retrieve Document Renditions  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_renditions_rendition_type_delete(self) -> None:
        """Test case for objects_documents_doc_id_renditions_rendition_type_delete

        Delete Single Document Rendition  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_renditions_rendition_type_get(self) -> None:
        """Test case for objects_documents_doc_id_renditions_rendition_type_get

        Download Document Rendition File  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_renditions_rendition_type_post(self) -> None:
        """Test case for objects_documents_doc_id_renditions_rendition_type_post

        Add Single Document Rendition  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_renditions_rendition_type_put(self) -> None:
        """Test case for objects_documents_doc_id_renditions_rendition_type_put

        Replace Document Rendition  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_roles_role_name_and_user_or_group_id_delete(self) -> None:
        """Test case for objects_documents_doc_id_roles_role_name_and_user_or_group_id_delete

        Remove Users & Groups from Roles on a Single Document  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_version_major_version_minor_version_attachments_get(self) -> None:
        """Test case for objects_documents_doc_id_version_major_version_minor_version_attachments_get

        Retrieve Document Version Attachments  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_get

        Retrieve Document Versions  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_annotations_annotation_id_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_annotations_annotation_id_get

        Read Annotations by ID  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_annotations_annotation_id_replies_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_annotations_annotation_id_replies_get

        Read Replies of Parent Annotation  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_annotations_file_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_annotations_file_get

        Export Document Version Annotations to PDF  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_annotations_file_post(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_annotations_file_post

        Import Document Version Annotations from PDF  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_annotations_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_annotations_get

        Read Annotations by Document Version and Type  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_attachments_attachment_id_versions_attachment_version_file_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_attachments_attachment_id_versions_attachment_version_file_get

        Download Document Version Attachment Version  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_attachments_attachment_id_versions_attachment_version_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_attachments_attachment_id_versions_attachment_version_get

        Retrieve Document Version Attachment Versions  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_delete(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_delete

        Delete Single Document Version  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_doc_export_annotations_to_csv_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_doc_export_annotations_to_csv_get

        Retrieve Document Version Notes as CSV  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_events_post(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_events_post

        Create Document Event  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_export_video_annotations_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_export_video_annotations_get

        Retrieve Video Annotations  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_file_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_file_get

        Download Document Version File  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_get

        Retrieve Document Version  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_put(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_put

        Update Document Version  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_relationships_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_relationships_get

        Retrieve Document Relationships  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_relationships_post(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_relationships_post

        Create Single Document Relationship  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_relationships_relationship_id_delete(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_relationships_relationship_id_delete

        Delete Single Document Relationship  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_relationships_relationship_id_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_relationships_relationship_id_get

        Retrieve Document Relationship  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_renditions_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_renditions_get

        Retrieve Document Version Renditions  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_renditions_rendition_type_delete(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_renditions_rendition_type_delete

        Delete Document Version Rendition  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_renditions_rendition_type_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_renditions_rendition_type_get

        Download Document Version Rendition File  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_renditions_rendition_type_post(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_renditions_rendition_type_post

        Upload Document Version Rendition  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_renditions_rendition_type_put(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_renditions_rendition_type_put

        Replace Document Version Rendition  # noqa: E501
        """
        pass

    def test_objects_documents_doc_id_versions_major_version_minor_version_thumbnail_get(self) -> None:
        """Test case for objects_documents_doc_id_versions_major_version_minor_version_thumbnail_get

        Download Document Version Thumbnail File  # noqa: E501
        """
        pass

    def test_objects_documents_get(self) -> None:
        """Test case for objects_documents_get

        Retrieve All Documents  # noqa: E501
        """
        pass

    def test_objects_documents_id_roles_get(self) -> None:
        """Test case for objects_documents_id_roles_get

        Retrieve All Document Roles  # noqa: E501
        """
        pass

    def test_objects_documents_id_roles_post(self) -> None:
        """Test case for objects_documents_id_roles_post

        Assign Users & Groups to Roles on a Single Document  # noqa: E501
        """
        pass

    def test_objects_documents_id_roles_role_name_get(self) -> None:
        """Test case for objects_documents_id_roles_role_name_get

        Retrieve Document Role  # noqa: E501
        """
        pass

    def test_objects_documents_id_versions_major_version_minor_version_lifecycle_actions_get(self) -> None:
        """Test case for objects_documents_id_versions_major_version_minor_version_lifecycle_actions_get

        Retrieve Document User Actions  # noqa: E501
        """
        pass

    def test_objects_documents_id_versions_major_version_minor_version_lifecycle_actions_name_v_entry_requirements_get(self) -> None:
        """Test case for objects_documents_id_versions_major_version_minor_version_lifecycle_actions_name_v_entry_requirements_get

        Retrieve Document Entry Criteria  # noqa: E501
        """
        pass

    def test_objects_documents_id_versions_major_version_minor_version_lifecycle_actions_name_v_put(self) -> None:
        """Test case for objects_documents_id_versions_major_version_minor_version_lifecycle_actions_name_v_put

        Initiate Document User Action  # noqa: E501
        """
        pass

    def test_objects_documents_lifecycle_actions_post(self) -> None:
        """Test case for objects_documents_lifecycle_actions_post

        Retrieve User Actions on Multiple Documents  # noqa: E501
        """
        pass

    def test_objects_documents_lifecycle_actions_user_action_name_put(self) -> None:
        """Test case for objects_documents_lifecycle_actions_user_action_name_put

        Initiate Bulk Document User Actions  # noqa: E501
        """
        pass

    def test_objects_documents_post(self) -> None:
        """Test case for objects_documents_post

        Create Single Document  # noqa: E501
        """
        pass

    def test_objects_documents_relationships_batch_delete(self) -> None:
        """Test case for objects_documents_relationships_batch_delete

        Delete Multiple Document Relationships  # noqa: E501
        """
        pass

    def test_objects_documents_relationships_batch_post(self) -> None:
        """Test case for objects_documents_relationships_batch_post

        Create Multiple Document Relationships  # noqa: E501
        """
        pass

    def test_objects_documents_renditions_batch_delete(self) -> None:
        """Test case for objects_documents_renditions_batch_delete

        Delete Multiple Document Renditions  # noqa: E501
        """
        pass

    def test_objects_documents_renditions_batch_post(self) -> None:
        """Test case for objects_documents_renditions_batch_post

        Add Multiple Document Renditions  # noqa: E501
        """
        pass

    def test_objects_documents_roles_batch_delete(self) -> None:
        """Test case for objects_documents_roles_batch_delete

        Remove Users and Groups from Roles on Multiple Documents & Binders  # noqa: E501
        """
        pass

    def test_objects_documents_roles_batch_post(self) -> None:
        """Test case for objects_documents_roles_batch_post

        Assign Users & Groups to Roles on Multiple Documents & Binders  # noqa: E501
        """
        pass

    def test_objects_documents_templates_get(self) -> None:
        """Test case for objects_documents_templates_get

        Retrieve Document Template Collection  # noqa: E501
        """
        pass

    def test_objects_documents_templates_post(self) -> None:
        """Test case for objects_documents_templates_post

        Create Single Document Template  # noqa: E501
        """
        pass

    def test_objects_documents_templates_put(self) -> None:
        """Test case for objects_documents_templates_put

        Update Multiple Document Templates  # noqa: E501
        """
        pass

    def test_objects_documents_templates_template_name_delete(self) -> None:
        """Test case for objects_documents_templates_template_name_delete

        Delete Basic Document Template  # noqa: E501
        """
        pass

    def test_objects_documents_templates_template_name_file_get(self) -> None:
        """Test case for objects_documents_templates_template_name_file_get

        Download Document Template File  # noqa: E501
        """
        pass

    def test_objects_documents_templates_template_name_get(self) -> None:
        """Test case for objects_documents_templates_template_name_get

        Retrieve Document Template Attributes  # noqa: E501
        """
        pass

    def test_objects_documents_templates_template_name_put(self) -> None:
        """Test case for objects_documents_templates_template_name_put

        Update Single Document Template  # noqa: E501
        """
        pass

    def test_objects_documents_tokens_post(self) -> None:
        """Test case for objects_documents_tokens_post

        Document Tokens  # noqa: E501
        """
        pass

    def test_objects_documents_versions_batch_actions_fileextract_post(self) -> None:
        """Test case for objects_documents_versions_batch_actions_fileextract_post

        Export Document Versions  # noqa: E501
        """
        pass

    def test_objects_documents_versions_batch_delete(self) -> None:
        """Test case for objects_documents_versions_batch_delete

        Delete Multiple Document Versions  # noqa: E501
        """
        pass

    def test_objects_documents_versions_batch_post(self) -> None:
        """Test case for objects_documents_versions_batch_post

        Create Multiple Document Versions  # noqa: E501
        """
        pass

    def test_objects_domain_get(self) -> None:
        """Test case for objects_domain_get

        Retrieve Domain Information  # noqa: E501
        """
        pass

    def test_objects_domains_get(self) -> None:
        """Test case for objects_domains_get

        Retrieve Domains  # noqa: E501
        """
        pass

    def test_objects_edl_matched_documents_batch_actions_add_post(self) -> None:
        """Test case for objects_edl_matched_documents_batch_actions_add_post

        Add EDL Matched Documents  # noqa: E501
        """
        pass

    def test_objects_edl_matched_documents_batch_actions_remove_post(self) -> None:
        """Test case for objects_edl_matched_documents_batch_actions_remove_post

        Remove EDL Matched Documents  # noqa: E501
        """
        pass

    def test_objects_groups_auto_get(self) -> None:
        """Test case for objects_groups_auto_get

        Retrieve Auto Managed Groups  # noqa: E501
        """
        pass

    def test_objects_groups_get(self) -> None:
        """Test case for objects_groups_get

        Retrieve All Groups  # noqa: E501
        """
        pass

    def test_objects_groups_group_id_delete(self) -> None:
        """Test case for objects_groups_group_id_delete

        Delete Group  # noqa: E501
        """
        pass

    def test_objects_groups_group_id_get(self) -> None:
        """Test case for objects_groups_group_id_get

        Retrieve Group  # noqa: E501
        """
        pass

    def test_objects_groups_group_id_put(self) -> None:
        """Test case for objects_groups_group_id_put

        Update Group  # noqa: E501
        """
        pass

    def test_objects_groups_post(self) -> None:
        """Test case for objects_groups_post

        Create Group   # noqa: E501
        """
        pass

    def test_objects_licenses_get(self) -> None:
        """Test case for objects_licenses_get

        Retrieve Application License Usage  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_actions_get(self) -> None:
        """Test case for objects_objectworkflows_actions_get

        Retrieve All Multi-Record Workflows  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_actions_workflow_name_get(self) -> None:
        """Test case for objects_objectworkflows_actions_workflow_name_get

        Retrieve Multi-Record Workflow Details  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_actions_workflow_name_post(self) -> None:
        """Test case for objects_objectworkflows_actions_workflow_name_post

        Initiate Multi-Record Workflow  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_get(self) -> None:
        """Test case for objects_objectworkflows_get

        Retrieve Workflows  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_get(self) -> None:
        """Test case for objects_objectworkflows_tasks_get

        Retrieve Workflow Tasks  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_task_id_actions_accept_post(self) -> None:
        """Test case for objects_objectworkflows_tasks_task_id_actions_accept_post

        Accept Single Record Workflow Task  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_task_id_actions_cancel_post(self) -> None:
        """Test case for objects_objectworkflows_tasks_task_id_actions_cancel_post

        Cancel Workflow Task  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_task_id_actions_complete_post(self) -> None:
        """Test case for objects_objectworkflows_tasks_task_id_actions_complete_post

        Complete Single Record Workflow Task  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_task_id_actions_get(self) -> None:
        """Test case for objects_objectworkflows_tasks_task_id_actions_get

        Retrieve Workflow Task Actions  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_task_id_actions_mdwaccept_post(self) -> None:
        """Test case for objects_objectworkflows_tasks_task_id_actions_mdwaccept_post

        Accept Multi-item Workflow Task  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_task_id_actions_mdwcomplete_post(self) -> None:
        """Test case for objects_objectworkflows_tasks_task_id_actions_mdwcomplete_post

        Complete Multi-item Workflow Task  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_task_id_actions_mdwmanagecontent_post(self) -> None:
        """Test case for objects_objectworkflows_tasks_task_id_actions_mdwmanagecontent_post

        Manage Multi-Item Workflow Content  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_task_id_actions_mdwreassign_post(self) -> None:
        """Test case for objects_objectworkflows_tasks_task_id_actions_mdwreassign_post

        Reassign Multi-item Workflow Task  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_task_id_actions_reassign_post(self) -> None:
        """Test case for objects_objectworkflows_tasks_task_id_actions_reassign_post

        Reassign Single Record Workflow Task  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_task_id_actions_task_action_get(self) -> None:
        """Test case for objects_objectworkflows_tasks_task_id_actions_task_action_get

        Retrieve Workflow Task Action Details  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_task_id_actions_undoaccept_post(self) -> None:
        """Test case for objects_objectworkflows_tasks_task_id_actions_undoaccept_post

        Undo Workflow Task Acceptance  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_task_id_actions_updateduedate_post(self) -> None:
        """Test case for objects_objectworkflows_tasks_task_id_actions_updateduedate_post

        Update Workflow Task Due Date  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_tasks_task_id_get(self) -> None:
        """Test case for objects_objectworkflows_tasks_task_id_get

        Retrieve Workflow Task Details  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_workflow_id_actions_get(self) -> None:
        """Test case for objects_objectworkflows_workflow_id_actions_get

        Retrieve Workflow Actions  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_workflow_id_actions_workflow_action_get(self) -> None:
        """Test case for objects_objectworkflows_workflow_id_actions_workflow_action_get

        Retrieve Workflow Action Details  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_workflow_id_actions_workflow_action_post(self) -> None:
        """Test case for objects_objectworkflows_workflow_id_actions_workflow_action_post

        Initiate Workflow Action  # noqa: E501
        """
        pass

    def test_objects_objectworkflows_workflow_id_get(self) -> None:
        """Test case for objects_objectworkflows_workflow_id_get

        Retrieve Workflow Details  # noqa: E501
        """
        pass

    def test_objects_picklists_get(self) -> None:
        """Test case for objects_picklists_get

        Retrieve All Picklists  # noqa: E501
        """
        pass

    def test_objects_picklists_picklist_name_get(self) -> None:
        """Test case for objects_picklists_picklist_name_get

        Retrieve Picklist Values  # noqa: E501
        """
        pass

    def test_objects_picklists_picklist_name_picklist_value_name_delete(self) -> None:
        """Test case for objects_picklists_picklist_name_picklist_value_name_delete

        Inactivate Picklist Value  # noqa: E501
        """
        pass

    def test_objects_picklists_picklist_name_picklist_value_name_put(self) -> None:
        """Test case for objects_picklists_picklist_name_picklist_value_name_put

        Update Picklist Value  # noqa: E501
        """
        pass

    def test_objects_picklists_picklist_name_post(self) -> None:
        """Test case for objects_picklists_picklist_name_post

        Create Picklist Values  # noqa: E501
        """
        pass

    def test_objects_picklists_picklist_name_put(self) -> None:
        """Test case for objects_picklists_picklist_name_put

        Update Picklist Value Label  # noqa: E501
        """
        pass

    def test_objects_sandbox_actions_buildproduction_post(self) -> None:
        """Test case for objects_sandbox_actions_buildproduction_post

        Build Production Vault  # noqa: E501
        """
        pass

    def test_objects_sandbox_actions_promoteproduction_post(self) -> None:
        """Test case for objects_sandbox_actions_promoteproduction_post

        Promote to Production  # noqa: E501
        """
        pass

    def test_objects_sandbox_actions_recheckusage_post(self) -> None:
        """Test case for objects_sandbox_actions_recheckusage_post

        Recheck Sandbox Usage Limit  # noqa: E501
        """
        pass

    def test_objects_sandbox_batch_changesize_post(self) -> None:
        """Test case for objects_sandbox_batch_changesize_post

        Change Sandbox Size  # noqa: E501
        """
        pass

    def test_objects_sandbox_entitlements_set_post(self) -> None:
        """Test case for objects_sandbox_entitlements_set_post

        Set Sandbox Entitlements  # noqa: E501
        """
        pass

    def test_objects_sandbox_get(self) -> None:
        """Test case for objects_sandbox_get

        Retrieve Sandboxes  # noqa: E501
        """
        pass

    def test_objects_sandbox_name_delete(self) -> None:
        """Test case for objects_sandbox_name_delete

        Delete Sandbox  # noqa: E501
        """
        pass

    def test_objects_sandbox_post(self) -> None:
        """Test case for objects_sandbox_post

        Create or Refresh Sandbox  # noqa: E501
        """
        pass

    def test_objects_sandbox_snapshot_api_name_actions_update_post(self) -> None:
        """Test case for objects_sandbox_snapshot_api_name_actions_update_post

        Update Sandbox Snapshot  # noqa: E501
        """
        pass

    def test_objects_sandbox_snapshot_api_name_actions_upgrade_post(self) -> None:
        """Test case for objects_sandbox_snapshot_api_name_actions_upgrade_post

        Upgrade Sandbox Snapshot  # noqa: E501
        """
        pass

    def test_objects_sandbox_snapshot_api_name_delete(self) -> None:
        """Test case for objects_sandbox_snapshot_api_name_delete

        Delete Sandbox Snapshot  # noqa: E501
        """
        pass

    def test_objects_sandbox_snapshot_get(self) -> None:
        """Test case for objects_sandbox_snapshot_get

        Retrieve Sandbox Snapshots  # noqa: E501
        """
        pass

    def test_objects_sandbox_snapshot_post(self) -> None:
        """Test case for objects_sandbox_snapshot_post

        Create Sandbox Snapshot  # noqa: E501
        """
        pass

    def test_objects_sandbox_vault_id_actions_refresh_post(self) -> None:
        """Test case for objects_sandbox_vault_id_actions_refresh_post

        Refresh Sandbox from Snapshot  # noqa: E501
        """
        pass

    def test_objects_sandbox_vault_id_get(self) -> None:
        """Test case for objects_sandbox_vault_id_get

        Retrieve Sandbox Details by ID  # noqa: E501
        """
        pass

    def test_objects_securitypolicies_get(self) -> None:
        """Test case for objects_securitypolicies_get

        Retrieve All Security Policies  # noqa: E501
        """
        pass

    def test_objects_securitypolicies_security_policy_name_get(self) -> None:
        """Test case for objects_securitypolicies_security_policy_name_get

        Retrieve Security Policy  # noqa: E501
        """
        pass

    def test_objects_users_get(self) -> None:
        """Test case for objects_users_get

        Retrieve All Users  # noqa: E501
        """
        pass

    def test_objects_users_id_get(self) -> None:
        """Test case for objects_users_id_get

        Retrieve User  # noqa: E501
        """
        pass

    def test_objects_users_id_permissions_get(self) -> None:
        """Test case for objects_users_id_permissions_get

        Retrieve User Permissions  # noqa: E501
        """
        pass

    def test_objects_users_id_put(self) -> None:
        """Test case for objects_users_id_put

        Update Single User  # noqa: E501
        """
        pass

    def test_objects_users_me_get(self) -> None:
        """Test case for objects_users_me_get

        Validate Session User  # noqa: E501
        """
        pass

    def test_objects_users_me_password_post(self) -> None:
        """Test case for objects_users_me_password_post

        Change My Password  # noqa: E501
        """
        pass

    def test_objects_users_me_permissions_get(self) -> None:
        """Test case for objects_users_me_permissions_get

        Retrieve My User Permissions  # noqa: E501
        """
        pass

    def test_objects_users_me_put(self) -> None:
        """Test case for objects_users_me_put

        Update My User  # noqa: E501
        """
        pass

    def test_objects_users_post(self) -> None:
        """Test case for objects_users_post

        Create Single User  # noqa: E501
        """
        pass

    def test_objects_users_put(self) -> None:
        """Test case for objects_users_put

        Update Multiple Users  # noqa: E501
        """
        pass

    def test_objects_users_user_id_delete(self) -> None:
        """Test case for objects_users_user_id_delete

        Disable User  # noqa: E501
        """
        pass

    def test_objects_users_user_id_vault_membership_vault_id_put(self) -> None:
        """Test case for objects_users_user_id_vault_membership_vault_id_put

        Update Vault Membership  # noqa: E501
        """
        pass

    def test_objects_vault_actions_compare_post(self) -> None:
        """Test case for objects_vault_actions_compare_post

        Vault Compare  # noqa: E501
        """
        pass

    def test_objects_vault_actions_configreport_post(self) -> None:
        """Test case for objects_vault_actions_configreport_post

        Vault Configuration Report  # noqa: E501
        """
        pass

    def test_query_components_post(self) -> None:
        """Test case for query_components_post

        Component Definition Query  # noqa: E501
        """
        pass

    def test_query_next_page_post(self) -> None:
        """Test case for query_next_page_post

        Next Page URL  # noqa: E501
        """
        pass

    def test_query_post(self) -> None:
        """Test case for query_post

        Submitting a Query  # noqa: E501
        """
        pass

    def test_query_previous_page_post(self) -> None:
        """Test case for query_previous_page_post

        Previous Page URL  # noqa: E501
        """
        pass

    def test_scim_v2_me_get(self) -> None:
        """Test case for scim_v2_me_get

        Retrieve Current User with SCIM  # noqa: E501
        """
        pass

    def test_scim_v2_me_put(self) -> None:
        """Test case for scim_v2_me_put

        Update Current User with SCIM  # noqa: E501
        """
        pass

    def test_scim_v2_resource_types_get(self) -> None:
        """Test case for scim_v2_resource_types_get

        Retrieve All SCIM Resource Types  # noqa: E501
        """
        pass

    def test_scim_v2_resource_types_type_get(self) -> None:
        """Test case for scim_v2_resource_types_type_get

        Retrieve Single SCIM Resource Type  # noqa: E501
        """
        pass

    def test_scim_v2_schemas_get(self) -> None:
        """Test case for scim_v2_schemas_get

        Retrieve All SCIM Schema Information  # noqa: E501
        """
        pass

    def test_scim_v2_schemas_id_get(self) -> None:
        """Test case for scim_v2_schemas_id_get

        Retrieve Single SCIM Schema Information  # noqa: E501
        """
        pass

    def test_scim_v2_service_provider_config_get(self) -> None:
        """Test case for scim_v2_service_provider_config_get

        Retrieve SCIM Provider  # noqa: E501
        """
        pass

    def test_scim_v2_type_get(self) -> None:
        """Test case for scim_v2_type_get

        Retrieve SCIM Resources  # noqa: E501
        """
        pass

    def test_scim_v2_type_id_get(self) -> None:
        """Test case for scim_v2_type_id_get

        Retrieve Single SCIM Resource  # noqa: E501
        """
        pass

    def test_scim_v2_users_get(self) -> None:
        """Test case for scim_v2_users_get

        Retrieve All Users with SCIM  # noqa: E501
        """
        pass

    def test_scim_v2_users_id_get(self) -> None:
        """Test case for scim_v2_users_id_get

        Retrieve Single User with SCIM  # noqa: E501
        """
        pass

    def test_scim_v2_users_id_put(self) -> None:
        """Test case for scim_v2_users_id_put

        Update User with SCIM  # noqa: E501
        """
        pass

    def test_scim_v2_users_post(self) -> None:
        """Test case for scim_v2_users_post

        Create User with SCIM  # noqa: E501
        """
        pass

    def test_services_certificate_cert_id_get(self) -> None:
        """Test case for services_certificate_cert_id_get

        Retrieve Signing Certificate  # noqa: E501
        """
        pass

    def test_services_configuration_mode_actions_disable_post(self) -> None:
        """Test case for services_configuration_mode_actions_disable_post

        Disable Configuration Mode  # noqa: E501
        """
        pass

    def test_services_configuration_mode_actions_enable_post(self) -> None:
        """Test case for services_configuration_mode_actions_enable_post

        Enable Configuration Mode  # noqa: E501
        """
        pass

    def test_services_directdata_files_get(self) -> None:
        """Test case for services_directdata_files_get

        Retrieve Available Direct Data Files  # noqa: E501
        """
        pass

    def test_services_directdata_files_name_get(self) -> None:
        """Test case for services_directdata_files_name_get

        Download Direct Data File  # noqa: E501
        """
        pass

    def test_services_file_staging_items_content_item_get(self) -> None:
        """Test case for services_file_staging_items_content_item_get

        Download Item Content  # noqa: E501
        """
        pass

    def test_services_file_staging_items_item_delete(self) -> None:
        """Test case for services_file_staging_items_item_delete

        Delete File or Folder  # noqa: E501
        """
        pass

    def test_services_file_staging_items_item_get(self) -> None:
        """Test case for services_file_staging_items_item_get

        List Items at a Path  # noqa: E501
        """
        pass

    def test_services_file_staging_items_item_put(self) -> None:
        """Test case for services_file_staging_items_item_put

        Update Folder or File  # noqa: E501
        """
        pass

    def test_services_file_staging_items_post(self) -> None:
        """Test case for services_file_staging_items_post

        Create Folder or File  # noqa: E501
        """
        pass

    def test_services_file_staging_upload_get(self) -> None:
        """Test case for services_file_staging_upload_get

        List Upload Sessions  # noqa: E501
        """
        pass

    def test_services_file_staging_upload_post(self) -> None:
        """Test case for services_file_staging_upload_post

        Create Resumable Upload Session  # noqa: E501
        """
        pass

    def test_services_file_staging_upload_upload_session_id_delete(self) -> None:
        """Test case for services_file_staging_upload_upload_session_id_delete

        Abort Upload Session  # noqa: E501
        """
        pass

    def test_services_file_staging_upload_upload_session_id_get(self) -> None:
        """Test case for services_file_staging_upload_upload_session_id_get

        Get Upload Session Details  # noqa: E501
        """
        pass

    def test_services_file_staging_upload_upload_session_id_parts_get(self) -> None:
        """Test case for services_file_staging_upload_upload_session_id_parts_get

        List File Parts Uploaded to Session  # noqa: E501
        """
        pass

    def test_services_file_staging_upload_upload_session_id_post(self) -> None:
        """Test case for services_file_staging_upload_upload_session_id_post

        Commit Upload Session  # noqa: E501
        """
        pass

    def test_services_file_staging_upload_upload_session_id_put(self) -> None:
        """Test case for services_file_staging_upload_upload_session_id_put

        Upload to a Session  # noqa: E501
        """
        pass

    def test_services_jobs_histories_get(self) -> None:
        """Test case for services_jobs_histories_get

        Retrieve Job Histories  # noqa: E501
        """
        pass

    def test_services_jobs_job_id_errors_get(self) -> None:
        """Test case for services_jobs_job_id_errors_get

        Retrieve Import Bulk Translation File Job Errors  # noqa: E501
        """
        pass

    def test_services_jobs_job_id_get(self) -> None:
        """Test case for services_jobs_job_id_get

        Retrieve Job Status  # noqa: E501
        """
        pass

    def test_services_jobs_job_id_summary_get(self) -> None:
        """Test case for services_jobs_job_id_summary_get

        Retrieve Import Bulk Translation File Job Summary  # noqa: E501
        """
        pass

    def test_services_jobs_job_id_tasks_get(self) -> None:
        """Test case for services_jobs_job_id_tasks_get

        Retrieve SDK Job Tasks  # noqa: E501
        """
        pass

    def test_services_jobs_monitors_get(self) -> None:
        """Test case for services_jobs_monitors_get

        Retrieve Job Monitors  # noqa: E501
        """
        pass

    def test_services_jobs_start_now_job_id_post(self) -> None:
        """Test case for services_jobs_start_now_job_id_post

        Start Job  # noqa: E501
        """
        pass

    def test_services_loader_extract_post(self) -> None:
        """Test case for services_loader_extract_post

        Extract Data Files  # noqa: E501
        """
        pass

    def test_services_loader_job_id_tasks_task_id_failurelog_get(self) -> None:
        """Test case for services_loader_job_id_tasks_task_id_failurelog_get

        Retrieve Load Failure Log Results  # noqa: E501
        """
        pass

    def test_services_loader_job_id_tasks_task_id_results_get(self) -> None:
        """Test case for services_loader_job_id_tasks_task_id_results_get

        Retrieve Loader Extract Results  # noqa: E501
        """
        pass

    def test_services_loader_job_id_tasks_task_id_results_renditions_get(self) -> None:
        """Test case for services_loader_job_id_tasks_task_id_results_renditions_get

        Retrieve Loader Extract Renditions Results  # noqa: E501
        """
        pass

    def test_services_loader_job_id_tasks_task_id_successlog_get(self) -> None:
        """Test case for services_loader_job_id_tasks_task_id_successlog_get

        Retrieve Load Success Log Results  # noqa: E501
        """
        pass

    def test_services_loader_load_post(self) -> None:
        """Test case for services_loader_load_post

        Load Data Objects  # noqa: E501
        """
        pass

    def test_services_package_actions_validate_post(self) -> None:
        """Test case for services_package_actions_validate_post

        Validate Package  # noqa: E501
        """
        pass

    def test_services_package_post(self) -> None:
        """Test case for services_package_post

        Export Package  # noqa: E501
        """
        pass

    def test_services_package_put(self) -> None:
        """Test case for services_package_put

        Import Package  # noqa: E501
        """
        pass

    def test_services_queues_get(self) -> None:
        """Test case for services_queues_get

        Retrieve All Queues  # noqa: E501
        """
        pass

    def test_services_queues_queue_name_actions_disable_delivery_put(self) -> None:
        """Test case for services_queues_queue_name_actions_disable_delivery_put

        Disable Delivery  # noqa: E501
        """
        pass

    def test_services_queues_queue_name_actions_enable_delivery_put(self) -> None:
        """Test case for services_queues_queue_name_actions_enable_delivery_put

        Enable Delivery  # noqa: E501
        """
        pass

    def test_services_queues_queue_name_actions_reset_put(self) -> None:
        """Test case for services_queues_queue_name_actions_reset_put

        Reset Queue  # noqa: E501
        """
        pass

    def test_services_queues_queue_name_get(self) -> None:
        """Test case for services_queues_queue_name_get

        Retrieve Queue Status  # noqa: E501
        """
        pass

    def test_services_vobject_vault_package_v_package_id_actions_validate_post(self) -> None:
        """Test case for services_vobject_vault_package_v_package_id_actions_validate_post

        Validate Imported Package  # noqa: E501
        """
        pass

    def test_session_delete(self) -> None:
        """Test case for session_delete

        End Session  # noqa: E501
        """
        pass

    def test_uicode_distributions_distribution_name_code_get(self) -> None:
        """Test case for uicode_distributions_distribution_name_code_get

        Download Single Client Code Distribution  # noqa: E501
        """
        pass

    def test_uicode_distributions_distribution_name_delete(self) -> None:
        """Test case for uicode_distributions_distribution_name_delete

        Delete Single Client Code Distribution  # noqa: E501
        """
        pass

    def test_uicode_distributions_distribution_name_get(self) -> None:
        """Test case for uicode_distributions_distribution_name_get

        Retrieve Single Client Code Distribution Metadata  # noqa: E501
        """
        pass

    def test_uicode_distributions_get(self) -> None:
        """Test case for uicode_distributions_get

        Retrieve All Client Code Distribution Metadata  # noqa: E501
        """
        pass

    def test_uicode_distributions_post(self) -> None:
        """Test case for uicode_distributions_post

        Add or Replace Single Client Code Distribution  # noqa: E501
        """
        pass

    def test_vobject_vault_package_v_package_id_actions_deploy_post(self) -> None:
        """Test case for vobject_vault_package_v_package_id_actions_deploy_post

        Deploy Package  # noqa: E501
        """
        pass

    def test_vobject_vault_package_v_package_id_actions_deploy_results_get(self) -> None:
        """Test case for vobject_vault_package_v_package_id_actions_deploy_results_get

        Retrieve Package Deploy Results  # noqa: E501
        """
        pass

    def test_vobjects_cascadedelete_results_object_name_job_status_job_id_get(self) -> None:
        """Test case for vobjects_cascadedelete_results_object_name_job_status_job_id_get

        Retrieve Results of Cascade Delete Job  # noqa: E501
        """
        pass

    def test_vobjects_deepcopy_results_object_name_job_status_job_id_get(self) -> None:
        """Test case for vobjects_deepcopy_results_object_name_job_status_job_id_get

        Retrieve Results of Deep Copy Job  # noqa: E501
        """
        pass

    def test_vobjects_edl_item_v_actions_createplaceholder_post(self) -> None:
        """Test case for vobjects_edl_item_v_actions_createplaceholder_post

        Create a Placeholder from an EDL Item  # noqa: E501
        """
        pass

    def test_vobjects_merges_job_id_log_get(self) -> None:
        """Test case for vobjects_merges_job_id_log_get

        Download Merge Records Job Log  # noqa: E501
        """
        pass

    def test_vobjects_merges_job_id_results_get(self) -> None:
        """Test case for vobjects_merges_job_id_results_get

        Retrieve Record Merge Results  # noqa: E501
        """
        pass

    def test_vobjects_merges_job_id_status_get(self) -> None:
        """Test case for vobjects_merges_job_id_status_get

        Retrieve Record Merge Status  # noqa: E501
        """
        pass

    def test_vobjects_object_name_actions_action_name_post(self) -> None:
        """Test case for vobjects_object_name_actions_action_name_post

        Initiate Object Action on Multiple Records  # noqa: E501
        """
        pass

    def test_vobjects_object_name_actions_changetype_post(self) -> None:
        """Test case for vobjects_object_name_actions_changetype_post

        Change Object Type  # noqa: E501
        """
        pass

    def test_vobjects_object_name_actions_merge_post(self) -> None:
        """Test case for vobjects_object_name_actions_merge_post

        Initiate Record Merge  # noqa: E501
        """
        pass

    def test_vobjects_object_name_actions_recalculaterollups_get(self) -> None:
        """Test case for vobjects_object_name_actions_recalculaterollups_get

        Retrieve Roll-up Field Recalculation Status  # noqa: E501
        """
        pass

    def test_vobjects_object_name_actions_recalculaterollups_post(self) -> None:
        """Test case for vobjects_object_name_actions_recalculaterollups_post

        Recalculate Roll-up Fields  # noqa: E501
        """
        pass

    def test_vobjects_object_name_actions_updatecorporatecurrency_put(self) -> None:
        """Test case for vobjects_object_name_actions_updatecorporatecurrency_put

        Update Corporate Currency Fields  # noqa: E501
        """
        pass

    def test_vobjects_object_name_attachments_batch_delete(self) -> None:
        """Test case for vobjects_object_name_attachments_batch_delete

        Delete Multiple Object Record Attachments  # noqa: E501
        """
        pass

    def test_vobjects_object_name_attachments_batch_post(self) -> None:
        """Test case for vobjects_object_name_attachments_batch_post

        Create Multiple Object Record Attachments  # noqa: E501
        """
        pass

    def test_vobjects_object_name_attachments_batch_put(self) -> None:
        """Test case for vobjects_object_name_attachments_batch_put

        Update Multiple Object Record Attachment Descriptions  # noqa: E501
        """
        pass

    def test_vobjects_object_name_delete(self) -> None:
        """Test case for vobjects_object_name_delete

        Delete Object Records  # noqa: E501
        """
        pass

    def test_vobjects_object_name_id_roles_role_name_get(self) -> None:
        """Test case for vobjects_object_name_id_roles_role_name_get

        Retrieve Object Record Roles  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_actions_action_name_get(self) -> None:
        """Test case for vobjects_object_name_object_record_id_actions_action_name_get

        Retrieve Object User Actions Details  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_actions_action_name_post(self) -> None:
        """Test case for vobjects_object_name_object_record_id_actions_action_name_post

        Initiate Object Action on a Single Record  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_actions_cascadedelete_post(self) -> None:
        """Test case for vobjects_object_name_object_record_id_actions_cascadedelete_post

        Cascade Delete Object Record  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_actions_deepcopy_post(self) -> None:
        """Test case for vobjects_object_name_object_record_id_actions_deepcopy_post

        Deep Copy Object Record  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_actions_get(self) -> None:
        """Test case for vobjects_object_name_object_record_id_actions_get

        Retrieve Object Record User Actions  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachment_fields_attachment_field_name_file_get(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachment_fields_attachment_field_name_file_get

        Download Attachment Field File  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachment_fields_attachment_field_name_file_post(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachment_fields_attachment_field_name_file_post

        Update Attachment Field File  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachment_fields_file_get(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachment_fields_file_get

        Download All Attachment Field Files  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachments_attachment_id_delete(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachments_attachment_id_delete

        Delete Object Record Attachment  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachments_attachment_id_get(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachments_attachment_id_get

        Retrieve Object Record Attachment Metadata  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachments_attachment_id_put(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachments_attachment_id_put

        Update Object Record Attachment Description  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachments_attachment_id_versions_attachment_version_delete(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachments_attachment_id_versions_attachment_version_delete

        Delete Object Record Attachment Version  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachments_attachment_id_versions_attachment_version_file_get(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachments_attachment_id_versions_attachment_version_file_get

        Download Object Record Attachment File  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachments_attachment_id_versions_attachment_version_get(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachments_attachment_id_versions_attachment_version_get

        Retrieve Object Record Attachment Version Metadata  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachments_attachment_id_versions_attachment_version_post(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachments_attachment_id_versions_attachment_version_post

        Restore Object Record Attachment Version  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachments_attachment_id_versions_get(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachments_attachment_id_versions_get

        Retrieve Object Record Attachment Versions  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachments_file_get(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachments_file_get

        Download All Object Record Attachment Files  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachments_get(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachments_get

        Retrieve Object Record Attachments  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_attachments_post(self) -> None:
        """Test case for vobjects_object_name_object_record_id_attachments_post

        Create Object Record Attachment  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_audittrail_get(self) -> None:
        """Test case for vobjects_object_name_object_record_id_audittrail_get

        Retrieve Complete Audit History for a Single Object Record  # noqa: E501
        """
        pass

    def test_vobjects_object_name_object_record_id_get(self) -> None:
        """Test case for vobjects_object_name_object_record_id_get

        Retrieve Object Record  # noqa: E501
        """
        pass

    def test_vobjects_object_name_post(self) -> None:
        """Test case for vobjects_object_name_post

        Create & Upsert Object Records  # noqa: E501
        """
        pass

    def test_vobjects_object_name_put(self) -> None:
        """Test case for vobjects_object_name_put

        Update Object Records  # noqa: E501
        """
        pass

    def test_vobjects_object_name_roles_delete(self) -> None:
        """Test case for vobjects_object_name_roles_delete

        Remove Users & Groups from Roles on Object Records  # noqa: E501
        """
        pass

    def test_vobjects_object_name_roles_post(self) -> None:
        """Test case for vobjects_object_name_roles_post

        Assign Users & Groups to Roles on Object Records  # noqa: E501
        """
        pass

    def test_vobjects_outbound_package_v_package_id_dependencies_get(self) -> None:
        """Test case for vobjects_outbound_package_v_package_id_dependencies_get

        Retrieve Outbound Package Dependencies  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
