# NOTE: This file is auto generated by OpenAPI Generator 7.14.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VeevaVaultAPIV251.Model.VobjectsObjectNameActionsMergePostRequestInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :duplicate_record_id,
    :main_record_id
  ]

  @type t :: %__MODULE__{
    :duplicate_record_id => String.t | nil,
    :main_record_id => String.t | nil
  }

  def decode(value) do
    value
  end
end

