=begin comment

Veeva Vault API v25.1

The latest GA version of the Vault REST API.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by the OpenAPI Generator
# Please update the test cases below to test the model.
# Ref: https://openapi-generator.tech
#
use Test::More;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;


use_ok('WWW::OpenAPIClient::Object::VobjectsObjectNameActionsMergePostRequestInner');

# uncomment below and update the test
#my $instance = WWW::OpenAPIClient::Object::VobjectsObjectNameActionsMergePostRequestInner->new();
#
#isa_ok($instance, 'WWW::OpenAPIClient::Object::VobjectsObjectNameActionsMergePostRequestInner');


done_testing();
