{-
   Veeva Vault API v25.1

   The latest GA version of the Vault REST API.

   OpenAPI Version: 3.0.0
   Veeva Vault API v25.1 API version: 1.0.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : VeevaVaultAPIV25.1.API
-}

module VeevaVaultAPIV25.1.API
  ( module VeevaVaultAPIV25.1.API.ApiDefault
  ) where

import VeevaVaultAPIV25.1.API.ApiDefault