/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.VobjectsObjectNameActionsMergePostRequestInner

class VobjectsObjectNameActionsMergePostRequestInnerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VobjectsObjectNameActionsMergePostRequestInner
        //val modelInstance = VobjectsObjectNameActionsMergePostRequestInner()

        // to test the property `duplicateRecordId`
        should("test duplicateRecordId") {
            // uncomment below to test the property
            //modelInstance.duplicateRecordId shouldBe ("TODO")
        }

        // to test the property `mainRecordId`
        should("test mainRecordId") {
            // uncomment below to test the property
            //modelInstance.mainRecordId shouldBe ("TODO")
        }

    }
}
