/** Veeva Vault API v25.1
  * The latest GA version of the Vault REST API.
  *
  * The version of the OpenAPI document: 1.0.0
  * Contact: team@openapitools.org
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package org.openapitools.client.models

import io.circe.*
import io.circe.syntax.*
import io.circe.{Decoder, Encoder}


/** 
  * @param duplicateRecordId 
  * @param mainRecordId 
  */
case class VobjectsObjectNameActionsMergePostRequestInner(
    duplicateRecordId: Option[String] = None,
    mainRecordId: Option[String] = None
)
  
object VobjectsObjectNameActionsMergePostRequestInner {
  given encoderVobjectsObjectNameActionsMergePostRequestInner: Encoder[VobjectsObjectNameActionsMergePostRequestInner] = Encoder.instance { t =>
    Json.fromFields{
      Seq(
        t.duplicateRecordId.map(v => "duplicate_record_id" -> v.asJson),
        t.mainRecordId.map(v => "main_record_id" -> v.asJson)
      ).flatten
    }
  }
  given decoderVobjectsObjectNameActionsMergePostRequestInner: Decoder[VobjectsObjectNameActionsMergePostRequestInner] = Decoder.instance { c =>
    for {
      duplicateRecordId <- c.downField("duplicate_record_id").as[Option[String]]
      mainRecordId <- c.downField("main_record_id").as[Option[String]]
    } yield VobjectsObjectNameActionsMergePostRequestInner(
      duplicateRecordId = duplicateRecordId,
      mainRecordId = mainRecordId
    )
  }
}

