--  Veeva Vault API v25.1
--  The latest GA version of the Vault REST API.
--
--  The version of the OpenAPI document: 1.0.0
--
--
--  NOTE: This package is auto generated by OpenAPI-Generator 7.14.0.
--  https://openapi-generator.tech
--  Do not edit the class manually.

with Swagger.Streams;
with Ada.Containers.Vectors;
package .Models is
   pragma Style_Checks ("-bmrIu");



   type VobjectsObjectNameActionsMergePostRequestInner_Type is
     record
       Duplicate_Record_Id : Swagger.Nullable_UString;
       Main_Record_Id : Swagger.Nullable_UString;
     end record;


   package VobjectsObjectNameActionsMergePostRequestInner_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => .Models.VobjectsObjectNameActionsMergePostRequestInner_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in .Models.VobjectsObjectNameActionsMergePostRequestInner_Type);
   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in VobjectsObjectNameActionsMergePostRequestInner_Type_Vectors.Vector);
   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out .Models.VobjectsObjectNameActionsMergePostRequestInner_Type);
   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : in out VobjectsObjectNameActionsMergePostRequestInner_Type_Vectors.Vector);


end .Models;
