/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAI_vobjects__object_name__actions_merge_post_request_inner.h
 *
 * 
 */

#ifndef OAI_vobjects__object_name__actions_merge_post_request_inner_H
#define OAI_vobjects__object_name__actions_merge_post_request_inner_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAI_vobjects__object_name__actions_merge_post_request_inner : public OAIObject {
public:
    OAI_vobjects__object_name__actions_merge_post_request_inner();
    OAI_vobjects__object_name__actions_merge_post_request_inner(QString json);
    ~OAI_vobjects__object_name__actions_merge_post_request_inner() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getDuplicateRecordId() const;
    void setDuplicateRecordId(const QString &duplicate_record_id);
    bool is_duplicate_record_id_Set() const;
    bool is_duplicate_record_id_Valid() const;

    QString getMainRecordId() const;
    void setMainRecordId(const QString &main_record_id);
    bool is_main_record_id_Set() const;
    bool is_main_record_id_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString m_duplicate_record_id;
    bool m_duplicate_record_id_isSet;
    bool m_duplicate_record_id_isValid;

    QString m_main_record_id;
    bool m_main_record_id_isSet;
    bool m_main_record_id_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAI_vobjects__object_name__actions_merge_post_request_inner)

#endif // OAI_vobjects__object_name__actions_merge_post_request_inner_H
