/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param duplicateRecordId 
 * @param mainRecordId 
 */


data class VobjectsObjectNameActionsMergePostRequestInner (

    @Json(name = "duplicate_record_id")
    val duplicateRecordId: kotlin.String? = null,

    @Json(name = "main_record_id")
    val mainRecordId: kotlin.String? = null

) {


}

