--  Veeva Vault API v25.1
--  The latest GA version of the Vault REST API.
--
--  The version of the OpenAPI document: 1.0.0
--
--
--  NOTE: This package is auto generated by OpenAPI-Generator 7.14.0.
--  https://openapi-generator.tech
--  Do not edit the class manually.

package body .Models is
   pragma Style_Checks ("-bmrIu");

   pragma Warnings (Off, "*use clause for package*");

   use Swagger.Streams;

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in .Models.VobjectsObjectNameActionsMergePostRequestInner_Type) is
   begin
      Into.Start_Entity (Name);
      if not Value.Duplicate_Record_Id.Is_Null then
         Into.Write_Entity ("duplicate_record_id", Value.Duplicate_Record_Id);
      end if;
      if not Value.Main_Record_Id.Is_Null then
         Into.Write_Entity ("main_record_id", Value.Main_Record_Id);
      end if;
      Into.End_Entity (Name);
   end Serialize;

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in VobjectsObjectNameActionsMergePostRequestInner_Type_Vectors.Vector) is
   begin
      Into.Start_Array (Name);
      for Item of Value loop
         Serialize (Into, "", Item);
      end loop;
      Into.End_Array (Name);
   end Serialize;

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out .Models.VobjectsObjectNameActionsMergePostRequestInner_Type) is
      Object : Swagger.Value_Type;
   begin
      Swagger.Streams.Deserialize (From, Name, Object);
      Swagger.Streams.Deserialize (Object, "duplicate_record_id", Value.Duplicate_Record_Id);
      Swagger.Streams.Deserialize (Object, "main_record_id", Value.Main_Record_Id);
   end Deserialize;

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : in out VobjectsObjectNameActionsMergePostRequestInner_Type_Vectors.Vector) is
      List : Swagger.Value_Array_Type;
      Item : .Models.VobjectsObjectNameActionsMergePostRequestInner_Type;
   begin
      Value.Clear;
      Swagger.Streams.Deserialize (From, Name, List);
      for Data of List loop
         Deserialize (Data, "", Item);
         Value.Append (Item);
      end loop;
   end Deserialize;


end .Models;
