/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VobjectsObjectNameActionsMergePostRequestInner model module.
 * @module model/VobjectsObjectNameActionsMergePostRequestInner
 * @version 1.0.0
 */
class VobjectsObjectNameActionsMergePostRequestInner {
    /**
     * Constructs a new <code>VobjectsObjectNameActionsMergePostRequestInner</code>.
     * @alias module:model/VobjectsObjectNameActionsMergePostRequestInner
     */
    constructor() { 
        
        VobjectsObjectNameActionsMergePostRequestInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VobjectsObjectNameActionsMergePostRequestInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VobjectsObjectNameActionsMergePostRequestInner} obj Optional instance to populate.
     * @return {module:model/VobjectsObjectNameActionsMergePostRequestInner} The populated <code>VobjectsObjectNameActionsMergePostRequestInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VobjectsObjectNameActionsMergePostRequestInner();

            if (data.hasOwnProperty('duplicate_record_id')) {
                obj['duplicate_record_id'] = ApiClient.convertToType(data['duplicate_record_id'], 'String');
            }
            if (data.hasOwnProperty('main_record_id')) {
                obj['main_record_id'] = ApiClient.convertToType(data['main_record_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>VobjectsObjectNameActionsMergePostRequestInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>VobjectsObjectNameActionsMergePostRequestInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['duplicate_record_id'] && !(typeof data['duplicate_record_id'] === 'string' || data['duplicate_record_id'] instanceof String)) {
            throw new Error("Expected the field `duplicate_record_id` to be a primitive type in the JSON string but got " + data['duplicate_record_id']);
        }
        // ensure the json data is a string
        if (data['main_record_id'] && !(typeof data['main_record_id'] === 'string' || data['main_record_id'] instanceof String)) {
            throw new Error("Expected the field `main_record_id` to be a primitive type in the JSON string but got " + data['main_record_id']);
        }

        return true;
    }


}



/**
 * @member {String} duplicate_record_id
 */
VobjectsObjectNameActionsMergePostRequestInner.prototype['duplicate_record_id'] = undefined;

/**
 * @member {String} main_record_id
 */
VobjectsObjectNameActionsMergePostRequestInner.prototype['main_record_id'] = undefined;






export default VobjectsObjectNameActionsMergePostRequestInner;

