//
// VobjectsObjectNameActionsMergePostRequestInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VobjectsObjectNameActionsMergePostRequestInner: Codable {
    public var duplicateRecordId: String?
    public var mainRecordId: String?

    public init(duplicateRecordId: String? = nil, mainRecordId: String? = nil) {
        self.duplicateRecordId = duplicateRecordId
        self.mainRecordId = mainRecordId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case duplicateRecordId = "duplicate_record_id"
        case mainRecordId = "main_record_id"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        duplicateRecordId = try container.decodeIfPresent(String.self, forKey: .duplicateRecordId)
        mainRecordId = try container.decodeIfPresent(String.self, forKey: .mainRecordId)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(duplicateRecordId, forKey: .duplicateRecordId)
        try container.encodeIfPresent(mainRecordId, forKey: .mainRecordId)
    }
}
