/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.14.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * _vobjects__object_name__actions_merge_post_request_inner.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL__vobjects__object_name__actions_merge_post_request_inner_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL__vobjects__object_name__actions_merge_post_request_inner_H_


#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



class  _vobjects__object_name__actions_merge_post_request_inner
    : public ModelBase
{
public:
    _vobjects__object_name__actions_merge_post_request_inner();
    virtual ~_vobjects__object_name__actions_merge_post_request_inner();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// _vobjects__object_name__actions_merge_post_request_inner members


    utility::string_t getDuplicateRecordId() const;
    bool duplicateRecordIdIsSet() const;
    void unsetDuplicate_record_id();
    void setDuplicateRecordId(const utility::string_t& value);

    utility::string_t getMainRecordId() const;
    bool mainRecordIdIsSet() const;
    void unsetMain_record_id();
    void setMainRecordId(const utility::string_t& value);


protected:
    utility::string_t m_Duplicate_record_id;
    bool m_Duplicate_record_idIsSet;

    utility::string_t m_Main_record_id;
    bool m_Main_record_idIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL__vobjects__object_name__actions_merge_post_request_inner_H_ */
