(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
      duplicate_record_id: string
          
           option [@default None]
        
        ; [@key "duplicate_record_id"]
      main_record_id: string
          
           option [@default None]
        
        ; [@key "main_record_id"]
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    duplicate_record_id = None;
    main_record_id = None;
}

