/*
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * VobjectsObjectNameActionsMergePostRequestInner
 */
@JsonPropertyOrder({
  VobjectsObjectNameActionsMergePostRequestInner.JSON_PROPERTY_DUPLICATE_RECORD_ID,
  VobjectsObjectNameActionsMergePostRequestInner.JSON_PROPERTY_MAIN_RECORD_ID
})
@JsonTypeName("_vobjects__object_name__actions_merge_post_request_inner")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2025-07-11T22:20:53.359841880Z[Etc/UTC]", comments = "Generator version: 7.14.0")
@Introspected
public class VobjectsObjectNameActionsMergePostRequestInner {
    public static final String JSON_PROPERTY_DUPLICATE_RECORD_ID = "duplicate_record_id";
    private String duplicateRecordId;

    public static final String JSON_PROPERTY_MAIN_RECORD_ID = "main_record_id";
    private String mainRecordId;

    public VobjectsObjectNameActionsMergePostRequestInner() {
    }

    public VobjectsObjectNameActionsMergePostRequestInner duplicateRecordId(String duplicateRecordId) {
        this.duplicateRecordId = duplicateRecordId;
        return this;
    }

    /**
     * Get duplicateRecordId
     * @return duplicateRecordId
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_DUPLICATE_RECORD_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getDuplicateRecordId() {
        return duplicateRecordId;
    }

    @JsonProperty(JSON_PROPERTY_DUPLICATE_RECORD_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDuplicateRecordId(String duplicateRecordId) {
        this.duplicateRecordId = duplicateRecordId;
    }

    public VobjectsObjectNameActionsMergePostRequestInner mainRecordId(String mainRecordId) {
        this.mainRecordId = mainRecordId;
        return this;
    }

    /**
     * Get mainRecordId
     * @return mainRecordId
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_MAIN_RECORD_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getMainRecordId() {
        return mainRecordId;
    }

    @JsonProperty(JSON_PROPERTY_MAIN_RECORD_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMainRecordId(String mainRecordId) {
        this.mainRecordId = mainRecordId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VobjectsObjectNameActionsMergePostRequestInner vobjectsObjectNameActionsMergePostRequestInner = (VobjectsObjectNameActionsMergePostRequestInner) o;
        return Objects.equals(this.duplicateRecordId, vobjectsObjectNameActionsMergePostRequestInner.duplicateRecordId) &&
            Objects.equals(this.mainRecordId, vobjectsObjectNameActionsMergePostRequestInner.mainRecordId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(duplicateRecordId, mainRecordId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class VobjectsObjectNameActionsMergePostRequestInner {\n");
        sb.append("    duplicateRecordId: ").append(toIndentedString(duplicateRecordId)).append("\n");
        sb.append("    mainRecordId: ").append(toIndentedString(mainRecordId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

