# coding: utf-8

# flake8: noqa
"""
    Veeva Vault API v25.1

    The latest GA version of the Vault REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.vobjects_object_name_actions_merge_post_request_inner import VobjectsObjectNameActionsMergePostRequestInner
