--[[
  Veeva Vault API v25.1

  The latest GA version of the Vault REST API.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.model._vobjects__object_name__actions_merge_post_request_inner
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("_vobjects__object_name__actions_merge_post_request_inner", function()
  local openapiclient__vobjects__object_name__actions_merge_post_request_inner = require "openapiclient.model._vobjects__object_name__actions_merge_post_request_inner"

  -- unit tests for the property 'duplicate_record_id'
  describe("property duplicate_record_id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'main_record_id'
  describe("property main_record_id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
