#
# Veeva Vault API v25.1
# The latest GA version of the Vault REST API.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER DuplicateRecordId
No description available.
.PARAMETER MainRecordId
No description available.
.OUTPUTS

VobjectsObjectNameActionsMergePostRequestInner<PSCustomObject>
#>

function Initialize-VobjectsObjectNameActionsMergePostRequestInner {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DuplicateRecordId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${MainRecordId}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => VobjectsObjectNameActionsMergePostRequestInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "duplicate_record_id" = ${DuplicateRecordId}
            "main_record_id" = ${MainRecordId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VobjectsObjectNameActionsMergePostRequestInner<PSCustomObject>

.DESCRIPTION

Convert from JSON to VobjectsObjectNameActionsMergePostRequestInner<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VobjectsObjectNameActionsMergePostRequestInner<PSCustomObject>
#>
function ConvertFrom-JsonToVobjectsObjectNameActionsMergePostRequestInner {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => VobjectsObjectNameActionsMergePostRequestInner' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in VobjectsObjectNameActionsMergePostRequestInner
        $AllProperties = ("duplicate_record_id", "main_record_id")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "duplicate_record_id"))) { #optional property not found
            $DuplicateRecordId = $null
        } else {
            $DuplicateRecordId = $JsonParameters.PSobject.Properties["duplicate_record_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "main_record_id"))) { #optional property not found
            $MainRecordId = $null
        } else {
            $MainRecordId = $JsonParameters.PSobject.Properties["main_record_id"].value
        }

        $PSO = [PSCustomObject]@{
            "duplicate_record_id" = ${DuplicateRecordId}
            "main_record_id" = ${MainRecordId}
        }

        return $PSO
    }

}

