/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIVobjectsObjectNameActionsMergePostRequestInner
 *
 * 
 */
class OPENAPI_API OpenAPIVobjectsObjectNameActionsMergePostRequestInner : public Model
{
public:
    virtual ~OpenAPIVobjectsObjectNameActionsMergePostRequestInner() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> DuplicateRecordId;
	TOptional<FString> MainRecordId;
};

}
