# coding: utf-8

"""
    Veeva Vault API v25.1

    The latest GA version of the Vault REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.vobjects_object_name_actions_merge_post_request_inner import VobjectsObjectNameActionsMergePostRequestInner  # noqa: E501

class TestVobjectsObjectNameActionsMergePostRequestInner(unittest.TestCase):
    """VobjectsObjectNameActionsMergePostRequestInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VobjectsObjectNameActionsMergePostRequestInner:
        """Test VobjectsObjectNameActionsMergePostRequestInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VobjectsObjectNameActionsMergePostRequestInner`
        """
        model = VobjectsObjectNameActionsMergePostRequestInner()  # noqa: E501
        if include_optional:
            return VobjectsObjectNameActionsMergePostRequestInner(
                duplicate_record_id = '',
                main_record_id = ''
            )
        else:
            return VobjectsObjectNameActionsMergePostRequestInner(
        )
        """

    def testVobjectsObjectNameActionsMergePostRequestInner(self):
        """Test VobjectsObjectNameActionsMergePostRequestInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
