#
# Veeva Vault API v25.1
# 
# The latest GA version of the Vault REST API.
# The version of the OpenAPI document: 1.0.0
# 
# Generated by: https://openapi-generator.tech
#

# Models
import openapiclient/models/model__vobjects__object_name__actions_merge_post_request_inner

export model__vobjects__object_name__actions_merge_post_request_inner

# APIs
import openapiclient/apis/api_default

export api_default
