#
# Veeva Vault API v25.1
# The latest GA version of the Vault REST API.
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'VobjectsObjectNameActionsMergePostRequestInner' {
    Context 'VobjectsObjectNameActionsMergePostRequestInner' {
        It 'Initialize-VobjectsObjectNameActionsMergePostRequestInner' {
            # a simple test to create an object
            #$NewObject = Initialize-VobjectsObjectNameActionsMergePostRequestInner -DuplicateRecordId "TEST_VALUE" -MainRecordId "TEST_VALUE"
            #$NewObject | Should -BeOfType VobjectsObjectNameActionsMergePostRequestInner
            #$NewObject.property | Should -Be 0
        }
    }
}
