/* tslint:disable */
/* eslint-disable */
/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VobjectsObjectNameActionsMergePostRequestInner
 */
export interface VobjectsObjectNameActionsMergePostRequestInner {
    /**
     * 
     * @type {string}
     * @memberof VobjectsObjectNameActionsMergePostRequestInner
     */
    duplicateRecordId?: string;
    /**
     * 
     * @type {string}
     * @memberof VobjectsObjectNameActionsMergePostRequestInner
     */
    mainRecordId?: string;
}

/**
 * Check if a given object implements the VobjectsObjectNameActionsMergePostRequestInner interface.
 */
export function instanceOfVobjectsObjectNameActionsMergePostRequestInner(value: object): value is VobjectsObjectNameActionsMergePostRequestInner {
    return true;
}

export function VobjectsObjectNameActionsMergePostRequestInnerFromJSON(json: any): VobjectsObjectNameActionsMergePostRequestInner {
    return VobjectsObjectNameActionsMergePostRequestInnerFromJSONTyped(json, false);
}

export function VobjectsObjectNameActionsMergePostRequestInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): VobjectsObjectNameActionsMergePostRequestInner {
    if (json == null) {
        return json;
    }
    return {
        
        'duplicateRecordId': json['duplicate_record_id'] == null ? undefined : json['duplicate_record_id'],
        'mainRecordId': json['main_record_id'] == null ? undefined : json['main_record_id'],
    };
}

export function VobjectsObjectNameActionsMergePostRequestInnerToJSON(json: any): VobjectsObjectNameActionsMergePostRequestInner {
    return VobjectsObjectNameActionsMergePostRequestInnerToJSONTyped(json, false);
}

export function VobjectsObjectNameActionsMergePostRequestInnerToJSONTyped(value?: VobjectsObjectNameActionsMergePostRequestInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duplicate_record_id': value['duplicateRecordId'],
        'main_record_id': value['mainRecordId'],
    };
}

