/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIVobjectsObjectNameActionsMergePostRequestInner.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIVobjectsObjectNameActionsMergePostRequestInner::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (DuplicateRecordId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("duplicate_record_id")); WriteJsonValue(Writer, DuplicateRecordId.GetValue());
	}
	if (MainRecordId.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("main_record_id")); WriteJsonValue(Writer, MainRecordId.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIVobjectsObjectNameActionsMergePostRequestInner::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("duplicate_record_id"), DuplicateRecordId);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("main_record_id"), MainRecordId);

	return ParseSuccess;
}

}
