/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIModule.h"

IMPLEMENT_MODULE(OpenAPIModule, OpenAPI);
DEFINE_LOG_CATEGORY(LogOpenAPI);

void OpenAPIModule::StartupModule()
{
}

void OpenAPIModule::ShutdownModule()
{
}
