# #Veeva Vault API v25.1
#
##The latest GA version of the Vault REST API.
#
#The version of the OpenAPI document: 1.0.0
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

require "../spec_helper"

# Unit tests for OpenAPIClient::VobjectsObjectNameActionsMergePostRequestInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
Spectator.describe OpenAPIClient::VobjectsObjectNameActionsMergePostRequestInner do

  describe "test an instance of VobjectsObjectNameActionsMergePostRequestInner" do
    skip "should create an instance of VobjectsObjectNameActionsMergePostRequestInner" do
      #instance = OpenAPIClient::VobjectsObjectNameActionsMergePostRequestInner.new
      #expect(instance).to be_instance_of(OpenAPIClient::VobjectsObjectNameActionsMergePostRequestInner)
    end
  end
  describe "test attribute 'duplicate_record_id'" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

  describe "test attribute 'main_record_id'" do
    skip "should work" do
      # assertion here. ref: https://crystal-lang.org/reference/guides/testing.html
    end
  end

end
