extends Resource
class_name VobjectsObjectNameActionsMergePostRequestInner

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# VobjectsObjectNameActionsMergePostRequestInner Model


# Required: False
# isArray: false
@export var duplicateUnderscorerecordUnderscoreid: String = "":
	set(value):
		__duplicateUnderscorerecordUnderscoreid__was__set = true
		duplicateUnderscorerecordUnderscoreid = value
var __duplicateUnderscorerecordUnderscoreid__was__set := false

# Required: False
# isArray: false
@export var mainUnderscorerecordUnderscoreid: String = "":
	set(value):
		__mainUnderscorerecordUnderscoreid__was__set = true
		mainUnderscorerecordUnderscoreid = value
var __mainUnderscorerecordUnderscoreid__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__duplicateUnderscorerecordUnderscoreid__was__set:
		bzz_dictionary["duplicateUnderscorerecordUnderscoreid"] = self.duplicateUnderscorerecordUnderscoreid
	if self.__mainUnderscorerecordUnderscoreid__was__set:
		bzz_dictionary["mainUnderscorerecordUnderscoreid"] = self.mainUnderscorerecordUnderscoreid
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("duplicateUnderscorerecordUnderscoreid"):
		me.duplicateUnderscorerecordUnderscoreid = from_dict["duplicateUnderscorerecordUnderscoreid"]
	if from_dict.has("mainUnderscorerecordUnderscoreid"):
		me.mainUnderscorerecordUnderscoreid = from_dict["mainUnderscorerecordUnderscoreid"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

