(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val api_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val api_mdl_components_component_type_and_record_name_files_get : component_type_and_record_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val api_mdl_components_component_type_and_record_name_get : component_type_and_record_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val api_mdl_execute_async_job_id_results_get : job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val api_mdl_execute_async_post : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val api_mdl_execute_post : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val api_mdl_files_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val audittrail_audit_trail_type_get : audit_trail_type:string -> ?start_date:string -> ?end_date:string -> ?all_dates:string -> ?format_result:string -> ?limit:string -> ?offset:string -> ?objects:string -> ?events:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val auth_discovery_post : ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val auth_oauth_session_oath_oidc_profile_id_post : oath_oidc_profile_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val auth_post : ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val code_class_name_delete : class_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val code_class_name_disable_put : class_name:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val code_class_name_enable_put : class_name:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val code_class_name_get : class_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val code_profiler_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val code_profiler_post : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val code_profiler_session_name_actions_end_post : session_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val code_profiler_session_name_delete : session_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val code_profiler_session_name_get : session_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val code_profiler_session_name_results_get : session_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val code_put : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val composites_trees_edl_hierarchy_or_template_actions_listnodes_post : edl_hierarchy_or_template:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val composites_trees_edl_hierarchy_or_template_get : edl_hierarchy_or_template:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val composites_trees_edl_hierarchy_v_parent_node_id_children_get : parent_node_id:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val composites_trees_edl_hierarchy_v_parent_node_id_children_put : parent_node_id:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val configuration_component_type_and_record_name_get : component_type_and_record_name:string -> ?loc:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val configuration_component_type_get : component_type:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val configuration_object_name_and_object_type_get : object_name_and_object_type:string -> ?loc:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val configuration_objecttype_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val configuration_role_assignment_rule_delete : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val configuration_role_assignment_rule_get : ?lifecycle__v:string -> ?role__v:string -> ?product__v:string -> ?country__v:string -> ?study__v:string -> ?study_country__v:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val configuration_role_assignment_rule_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val configuration_role_assignment_rule_put : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val delegation_login_post : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val delegation_vaults_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val keep_alive_post : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val limits_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val logs_api_usage_get : ?date:string -> ?log_format:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val logs_code_debug_get : ?user_id:string -> ?include_inactive:bool -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val logs_code_debug_id_actions_reset_delete : id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val logs_code_debug_id_actions_reset_post : id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val logs_code_debug_id_files_get : id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val logs_code_debug_id_get : id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val logs_code_debug_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val logs_code_runtime_get : ?date:string -> ?log_format:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val messages_message_type_actions_import_post : message_type:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val messages_message_type_language_lang_actions_export_post : message_type:string -> lang:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_audittrail_audit_trail_type_get : audit_trail_type:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_audittrail_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_components_component_type_get : component_type:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_components_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_binders_templates_bindernodes_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_binders_templates_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_annotations_placemarks_types_placemark_type_get : placemark_type:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_annotations_references_types_reference_type_get : reference_type:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_annotations_types_annotation_type_get : annotation_type:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_events_event_type_types_event_subtype_get : event_type:string -> event_subtype:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_events_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_lock_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_properties_find_common_post : ?content_type:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_properties_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_templates_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_types_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_types_type_get : _type:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_types_type_relationships_get : _type:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_types_type_subtypes_subtype_classifications_classification_get : _type:string -> subtype:string -> classification:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_documents_types_type_subtypes_subtype_get : _type:string -> subtype:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_groups_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_securitypolicies_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_objects_users_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_query_archived_documents_relationships_document_signature_sysr_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_query_documents_relationships_document_signature_sysr_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_vobjects_get : ?loc:bool -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_vobjects_object_name_actions_canceldeployment_post : object_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_vobjects_object_name_fields_object_field_name_get : object_name:string -> object_field_name:string -> ?loc:bool -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_vobjects_object_name_get : object_name:string -> ?loc:bool -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_vobjects_object_name_page_layouts_get : object_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val metadata_vobjects_object_name_page_layouts_layout_name_get : object_name:string -> layout_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val notifications_histories_get : ?start_date:string -> ?end_date:string -> ?all_dates:bool -> ?format_result:string -> ?limit:string -> ?offset:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val object_workflow_actions_action_get : action:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val object_workflow_actions_action_post : action:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val object_workflow_actions_canceltasks_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val object_workflow_actions_cancelworkflows_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val object_workflow_actions_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val object_workflow_actions_reassigntasks_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val object_workflow_actions_replaceworkflowowner_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_actions_export_job_id_results_get : job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_actions_export_post : binder_id:string -> ?source:bool -> ?renditiontype:string -> ?docversion:string -> ?attachments:string -> ?export:string -> ?docfield:bool -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_actions_post : binder_id:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_binding_rule_put : binder_id:string -> ?content_type:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_delete : binder_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_documents_node_id_binding_rule_put : binder_id:string -> node_id:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_documents_post : binder_id:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_documents_section_id_delete : binder_id:string -> section_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_documents_section_id_put : binder_id:string -> section_id:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_get : binder_id:string -> ?depth:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_post : binder_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_put : binder_id:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_roles_role_name_and_user_or_group_id_delete : binder_id:string -> role_name_and_user_or_group:string -> id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_sections_node_id_binding_rule_put : binder_id:string -> node_id:string -> ?content_type:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_sections_node_id_put : binder_id:string -> node_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_sections_post : binder_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_sections_section_id_delete : binder_id:string -> section_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_sections_section_id_get : binder_id:string -> section_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_versions_get : binder_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_versions_major_version_minor_version_actions_export_post : binder_id:string -> major_version:string -> minor_version:string -> ?source:bool -> ?renditiontype:string -> ?docversion:string -> ?attachments:string -> ?export:string -> ?docfield:bool -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_versions_major_version_minor_version_delete : binder_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_versions_major_version_minor_version_get : binder_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_versions_major_version_minor_version_put : binder_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_versions_major_version_minor_version_relationships_post : binder_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_versions_major_version_minor_version_relationships_relationship_id_delete : binder_id:string -> major_version:string -> minor_version:string -> relationship_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_versions_major_version_minor_version_relationships_relationship_id_get : binder_id:string -> major_version:string -> minor_version:string -> relationship_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_binder_id_versions_major_version_minor_version_sections_section_id_get : binder_id:string -> major_version:string -> minor_version:string -> section_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_id_roles_get : id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_id_roles_post : id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_id_roles_role_name_get : id:string -> role_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_id_versions_major_version_minor_version_lifecycle_actions_get : id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_id_versions_major_version_minor_version_lifecycle_actions_name_v_entry_requirements_get : id:string -> major_version:string -> minor_version:string -> name__v:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_id_versions_major_version_minor_version_lifecycle_actions_name_v_put : id:string -> major_version:string -> minor_version:string -> name__v:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_lifecycle_actions_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_lifecycle_actions_user_action_name_put : user_action_name:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_post : ?async:bool -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_templates_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_templates_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_templates_put : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_templates_template_name_bindernodes_get : template_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_templates_template_name_bindernodes_post : template_name:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_templates_template_name_bindernodes_put : template_name:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_templates_template_name_delete : template_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_binders_templates_template_name_get : template_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_deletions_documents_get : ?start_date:string -> ?end_date:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_deletions_vobjects_object_name_get : object_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_actions_get : ?loc:bool -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_actions_lifecycle_and_state_and_action_job_id_results_get : lifecycle_and_state_and_action:string -> job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_actions_workflow_name_get : workflow_name:string -> ?loc:bool -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_actions_workflow_name_post : workflow_name:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_annotations_batch_delete : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_annotations_batch_post : authorization:string -> content_type:string -> accept:string -> x_vault_api_client_id:string -> unit Lwt.t
val objects_documents_annotations_batch_put : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_annotations_replies_batch_post : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_attachments_batch_delete : ?accept:string -> ?authorization:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_attachments_batch_post : ?accept:string -> ?authorization:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_attachments_batch_put : ?accept:string -> ?authorization:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_batch_actions_fileextract_job_id_results_get : job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_batch_actions_fileextract_post : ?source:bool -> ?renditions:bool -> ?allversions:bool -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_batch_actions_reclassify_put : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_migration_mode:bool -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_batch_actions_rerender_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_batch_delete : ?id_param:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_batch_lock_delete : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_batch_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_migration_mode:bool -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_batch_put : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_migration_mode:bool -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_anchors_get : doc_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_annotations_file_get : doc_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_annotations_file_post : doc_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_attachments_attachment_id_delete : doc_id:string -> attachment_id:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_attachments_attachment_id_file_get : doc_id:string -> attachment_id:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_attachments_attachment_id_get : doc_id:string -> attachment_id:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_attachments_attachment_id_put : doc_id:string -> attachment_id:string -> ?accept:string -> ?authorization:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_attachments_attachment_id_versions_attachment_version_delete : doc_id:string -> attachment_id:string -> attachment_version:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_attachments_attachment_id_versions_attachment_version_file_get : doc_id:string -> attachment_id:string -> attachment_version:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_attachments_attachment_id_versions_attachment_version_get : doc_id:string -> attachment_id:string -> attachment_version:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_attachments_attachment_id_versions_attachment_version_post : doc_id:string -> attachment_id:string -> attachment_version:string -> ?restore:bool -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_attachments_attachment_id_versions_get : doc_id:string -> attachment_id:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_attachments_file_get : doc_id:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_attachments_get : doc_id:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_attachments_post : doc_id:string -> ?accept:string -> ?authorization:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_audittrail_get : doc_id:string -> ?start_date:string -> ?end_date:string -> ?format_result:string -> ?limit:string -> ?offset:string -> ?events:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_delete : doc_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_events_get : doc_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_file_get : doc_id:string -> ?lock_document:bool -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_get : doc_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_lock_delete : doc_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_lock_get : doc_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_lock_post : doc_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_major_version_minor_version_attachments_file_get : doc_id:string -> major_version:string -> minor_version:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_post : doc_id:string -> ?suppress_rendition:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_put : doc_id:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_migration_mode:bool -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_renditions_get : doc_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_renditions_rendition_type_delete : doc_id:string -> rendition_type:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_renditions_rendition_type_get : doc_id:string -> rendition_type:string -> ?steady_state:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_renditions_rendition_type_post : doc_id:string -> rendition_type:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_renditions_rendition_type_put : doc_id:string -> rendition_type:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_roles_role_name_and_user_or_group_id_delete : doc_id:string -> role_name_and_user_or_group:string -> id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_version_major_version_minor_version_attachments_get : doc_id:string -> major_version:string -> minor_version:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_get : doc_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_annotations_annotation_id_get : doc_id:string -> major_version:string -> minor_version:string -> annotation_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_annotations_annotation_id_replies_get : doc_id:string -> major_version:string -> minor_version:string -> annotation_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_annotations_file_get : doc_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_annotations_file_post : doc_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_annotations_get : doc_id:string -> major_version:string -> minor_version:string -> ?limit:string -> ?offset:string -> ?annotation_types:string -> ?pagination_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_attachments_attachment_id_versions_attachment_version_file_get : doc_id:string -> major_version:string -> minor_version:string -> attachment_id:string -> attachment_version:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_attachments_attachment_id_versions_attachment_version_get : doc_id:string -> major_version:string -> minor_version:string -> attachment_id:string -> attachment_version:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_delete : doc_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_doc_export_annotations_to_csv_get : doc_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_events_post : doc_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_export_video_annotations_get : doc_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_file_get : doc_id:string -> major_version:string -> minor_version:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_get : doc_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_put : doc_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_migration_mode:bool -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_relationships_get : doc_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_relationships_post : doc_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_relationships_relationship_id_delete : doc_id:string -> major_version:string -> minor_version:string -> relationship_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_relationships_relationship_id_get : doc_id:string -> major_version:string -> minor_version:string -> relationship_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_renditions_get : doc_id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_renditions_rendition_type_delete : doc_id:string -> major_version:string -> minor_version:string -> rendition_type:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_renditions_rendition_type_get : doc_id:string -> major_version:string -> minor_version:string -> rendition_type:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_renditions_rendition_type_post : doc_id:string -> major_version:string -> minor_version:string -> rendition_type:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_renditions_rendition_type_put : doc_id:string -> major_version:string -> minor_version:string -> rendition_type:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_doc_id_versions_major_version_minor_version_thumbnail_get : doc_id:string -> major_version:string -> minor_version:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_get : ?named_filter:string -> ?scope:string -> ?versionscope:string -> ?search:string -> ?limit:string -> ?sort:string -> ?start:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_id_roles_get : id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_id_roles_post : id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_id_roles_role_name_get : id:string -> role_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_id_versions_major_version_minor_version_lifecycle_actions_get : id:string -> major_version:string -> minor_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_id_versions_major_version_minor_version_lifecycle_actions_name_v_entry_requirements_get : id:string -> major_version:string -> minor_version:string -> name__v:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_id_versions_major_version_minor_version_lifecycle_actions_name_v_put : id:string -> major_version:string -> minor_version:string -> name__v:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_lifecycle_actions_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_lifecycle_actions_user_action_name_put : user_action_name:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_post : ?authorization:string -> ?accept:string -> ?x_vault_api_migration_mode:bool -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_relationships_batch_delete : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_relationships_batch_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_renditions_batch_delete : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_renditions_batch_post : ?id_param:string -> ?large_size_asset:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_migration_mode:bool -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_roles_batch_delete : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_roles_batch_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_templates_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_templates_post : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_templates_put : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_templates_template_name_delete : template_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_templates_template_name_file_get : template_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_templates_template_name_get : template_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_templates_template_name_put : template_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_tokens_post : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_versions_batch_actions_fileextract_post : ?source:bool -> ?renditions:bool -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_versions_batch_delete : ?id_param:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_documents_versions_batch_post : ?id_param:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_migration_mode:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_domain_get : ?include_application:bool -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_domains_get : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_edl_matched_documents_batch_actions_add_post : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_edl_matched_documents_batch_actions_remove_post : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_groups_auto_get : ?limit:string -> ?offset:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_groups_get : ?include_implied:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_groups_group_id_delete : group_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_groups_group_id_get : group_id:string -> ?include_implied:bool -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_groups_group_id_put : group_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_groups_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_licenses_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_actions_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_actions_workflow_name_get : workflow_name:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_actions_workflow_name_post : workflow_name:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_get : ?object__v:string -> ?record_id__v:string -> ?participant:string -> ?status__v:string -> ?offset:string -> ?page_size:string -> ?loc:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_get : ?object__v:string -> ?record_id__v:string -> ?assignee__v:string -> ?status__v:string -> ?offset:string -> ?page_size:string -> ?loc:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_task_id_actions_accept_post : task_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_task_id_actions_cancel_post : task_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_task_id_actions_complete_post : task_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_task_id_actions_get : task_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_task_id_actions_mdwaccept_post : task_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_task_id_actions_mdwcomplete_post : task_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_task_id_actions_mdwmanagecontent_post : task_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_task_id_actions_mdwreassign_post : task_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_task_id_actions_reassign_post : task_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_task_id_actions_task_action_get : task_id:string -> task_action:string -> ?loc:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_task_id_actions_undoaccept_post : task_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_task_id_actions_updateduedate_post : task_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_tasks_task_id_get : task_id:string -> ?loc:bool -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_workflow_id_actions_get : workflow_id:string -> ?loc:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_workflow_id_actions_workflow_action_get : workflow_id:string -> workflow_action:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_workflow_id_actions_workflow_action_post : workflow_id:string -> workflow_action:string -> ?documents__sys:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_objectworkflows_workflow_id_get : workflow_id:string -> ?loc:bool -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_picklists_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_picklists_picklist_name_get : picklist_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_picklists_picklist_name_picklist_value_name_delete : picklist_name:string -> picklist_value_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_picklists_picklist_name_picklist_value_name_put : picklist_name:string -> picklist_value_name:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_picklists_picklist_name_post : picklist_name:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_picklists_picklist_name_put : picklist_name:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_actions_buildproduction_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_actions_promoteproduction_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_actions_recheckusage_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_batch_changesize_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_entitlements_set_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_name_delete : name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_snapshot_api_name_actions_update_post : api_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_snapshot_api_name_actions_upgrade_post : api_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_snapshot_api_name_delete : api_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_snapshot_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_snapshot_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_vault_id_actions_refresh_post : vault_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_sandbox_vault_id_get : vault_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_securitypolicies_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_securitypolicies_security_policy_name_get : security_policy_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_users_get : ?vaults:string -> ?exclude_vault_membership:string -> ?exclude_app_licensing:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_users_id_get : id:string -> ?exclude_vault_membership:string -> ?exclude_app_licensing:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_users_id_permissions_get : id:string -> ?filter:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_users_id_put : id:string -> ?authorization:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_users_me_get : ?exclude_vault_membership:string -> ?exclude_app_licensing:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_users_me_password_post : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_users_me_permissions_get : ?filter:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_users_me_put : ?authorization:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_users_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_users_put : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_users_user_id_delete : user_id:string -> ?domain:bool -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_users_user_id_vault_membership_vault_id_put : user_id:string -> vault_id:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_vault_actions_compare_post : ?authorization:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val objects_vault_actions_configreport_post : ?authorization:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val query_components_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val query_next_page_post : next_page:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_describe_query:bool -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val query_post : ?authorization:string -> ?accept:string -> ?x_vault_api_describe_query:bool -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val query_previous_page_post : previous_page:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_describe_query:bool -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val scim_v2_me_get : ?attributes:string -> ?excluded_attributes:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val scim_v2_me_put : ?attributes:string -> ?excluded_attributes:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val scim_v2_resource_types_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val scim_v2_resource_types_type_get : _type:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val scim_v2_schemas_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val scim_v2_schemas_id_get : id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val scim_v2_service_provider_config_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val scim_v2_type_get : _type:string -> ?filter:string -> ?attributes:string -> ?excluded_attributes:string -> ?sort_by:string -> ?sort_order:string -> ?start_index:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val scim_v2_type_id_get : _type:string -> id:string -> ?attributes:string -> ?excluded_attributes:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val scim_v2_users_get : ?filter:string -> ?attributes:string -> ?excluded_attributes:string -> ?sort_by:string -> ?sort_order:string -> ?count:string -> ?start_index:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val scim_v2_users_id_get : id:string -> ?filter:string -> ?attributes:string -> ?excluded_attributes:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val scim_v2_users_id_put : id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val scim_v2_users_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_certificate_cert_id_get : cert_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_configuration_mode_actions_disable_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_configuration_mode_actions_enable_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_directdata_files_get : ?extract_type:string -> ?start_time:int32 -> ?stop_time:int32 -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_directdata_files_name_get : name:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_file_staging_items_content_item_get : item:string -> ?authorization:string -> ?accept:string -> ?range:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_file_staging_items_item_delete : item:string -> ?recursive:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_file_staging_items_item_get : item:string -> ?recursive:string -> ?limit:string -> ?format_result:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_file_staging_items_item_put : item:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_file_staging_items_post : ?authorization:string -> ?accept:string -> ?content_md5:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_file_staging_upload_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_file_staging_upload_post : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_file_staging_upload_upload_session_id_delete : upload_session_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_file_staging_upload_upload_session_id_get : upload_session_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_file_staging_upload_upload_session_id_parts_get : upload_session_id:string -> ?limit:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_file_staging_upload_upload_session_id_post : upload_session_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_file_staging_upload_upload_session_id_put : upload_session_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_file_part_number:string -> ?content_md5:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_jobs_histories_get : ?start_date:string -> ?end_date:string -> ?status:string -> ?limit:string -> ?offset:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_jobs_job_id_errors_get : job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_jobs_job_id_get : job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_jobs_job_id_summary_get : job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_jobs_job_id_tasks_get : job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_jobs_monitors_get : ?start_date:string -> ?end_date:string -> ?status:string -> ?limit:string -> ?offset:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_jobs_start_now_job_id_post : job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_loader_extract_post : ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_loader_job_id_tasks_task_id_failurelog_get : job_id:string -> task_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_loader_job_id_tasks_task_id_results_get : job_id:string -> task_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_loader_job_id_tasks_task_id_results_renditions_get : job_id:string -> task_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_loader_job_id_tasks_task_id_successlog_get : job_id:string -> task_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_loader_load_post : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_package_actions_validate_post : ?authorization:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_package_post : ?authorization:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_package_put : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_queues_get : ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_queues_queue_name_actions_disable_delivery_put : queue_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_queues_queue_name_actions_enable_delivery_put : queue_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_queues_queue_name_actions_reset_put : queue_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_queues_queue_name_get : queue_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val services_vobject_vault_package_v_package_id_actions_validate_post : package_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val session_delete : ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val uicode_distributions_distribution_name_code_get : distribution_name:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val uicode_distributions_distribution_name_delete : distribution_name:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val uicode_distributions_distribution_name_get : distribution_name:string -> ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val uicode_distributions_get : ?accept:string -> ?authorization:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val uicode_distributions_post : ?accept:string -> ?authorization:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobject_vault_package_v_package_id_actions_deploy_post : package_id:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobject_vault_package_v_package_id_actions_deploy_results_get : package_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_cascadedelete_results_object_name_job_status_job_id_get : object_name:string -> job_status:string -> job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_deepcopy_results_object_name_job_status_job_id_get : object_name:string -> job_status:string -> job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_edl_item_v_actions_createplaceholder_post : ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_merges_job_id_log_get : job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_merges_job_id_results_get : job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_merges_job_id_status_get : job_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_actions_action_name_post : object_name:string -> action_name:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_actions_changetype_post : object_name:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_actions_merge_post : object_name:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> model__vobjects__object_name__actions_merge_post_request_inner:Model__vobjects__object_name__actions_merge_post_request_inner.t list -> unit -> unit Lwt.t
val vobjects_object_name_actions_recalculaterollups_get : object_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_actions_recalculaterollups_post : object_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_actions_updatecorporatecurrency_put : object_name:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_attachments_batch_delete : object_name:string -> ?id_param:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_attachments_batch_post : object_name:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_attachments_batch_put : object_name:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_delete : object_name:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_id_roles_role_name_get : object_name:string -> id:string -> role_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_actions_action_name_get : object_name:string -> object_record_id:string -> action_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_actions_action_name_post : object_name:string -> object_record_id:string -> action_name:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_actions_cascadedelete_post : object_name:string -> object_record_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_actions_deepcopy_post : object_name:string -> object_record_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_actions_get : object_name:string -> object_record_id:string -> ?loc:bool -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachment_fields_attachment_field_name_file_get : object_name:string -> object_record_id:string -> attachment_field_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachment_fields_attachment_field_name_file_post : object_name:string -> object_record_id:string -> attachment_field_name:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachment_fields_file_get : object_name:string -> object_record_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachments_attachment_id_delete : object_name:string -> object_record_id:string -> attachment_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachments_attachment_id_get : object_name:string -> object_record_id:string -> attachment_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachments_attachment_id_put : object_name:string -> object_record_id:string -> attachment_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachments_attachment_id_versions_attachment_version_delete : object_name:string -> object_record_id:string -> attachment_id:string -> attachment_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachments_attachment_id_versions_attachment_version_file_get : object_name:string -> object_record_id:string -> attachment_id:string -> attachment_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachments_attachment_id_versions_attachment_version_get : object_name:string -> object_record_id:string -> attachment_id:string -> attachment_version:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachments_attachment_id_versions_attachment_version_post : object_name:string -> object_record_id:string -> attachment_id:string -> attachment_version:string -> ?restore:bool -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachments_attachment_id_versions_get : object_name:string -> object_record_id:string -> attachment_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachments_file_get : object_name:string -> object_record_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachments_get : object_name:string -> object_record_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_attachments_post : object_name:string -> object_record_id:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_audittrail_get : object_name:string -> object_record_id:string -> ?start_date:string -> ?end_date:string -> ?format_result:string -> ?limit:string -> ?offset:string -> ?events:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_object_record_id_get : object_name:string -> object_record_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_post : object_name:string -> ?id_param:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_migration_mode:bool -> ?x_vault_api_no_triggers:bool -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_put : object_name:string -> ?authorization:string -> ?content_type:string -> ?accept:string -> ?x_vault_api_migration_mode:bool -> ?x_vault_api_no_triggers:bool -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_roles_delete : object_name:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_object_name_roles_post : object_name:string -> ?authorization:string -> ?accept:string -> ?content_type:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
val vobjects_outbound_package_v_package_id_dependencies_get : package_id:string -> ?authorization:string -> ?accept:string -> ?x_vault_api_client_id:string -> unit -> unit Lwt.t
