/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.VeevaVaultApiV251);
  }
}(this, function(expect, VeevaVaultApiV251) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new VeevaVaultApiV251.VobjectsObjectNameActionsMergePostRequestInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VobjectsObjectNameActionsMergePostRequestInner', function() {
    it('should create an instance of VobjectsObjectNameActionsMergePostRequestInner', function() {
      // uncomment below and update the code to test VobjectsObjectNameActionsMergePostRequestInner
      //var instance = new VeevaVaultApiV251.VobjectsObjectNameActionsMergePostRequestInner();
      //expect(instance).to.be.a(VeevaVaultApiV251.VobjectsObjectNameActionsMergePostRequestInner);
    });

    it('should have the property duplicateRecordId (base name: "duplicate_record_id")', function() {
      // uncomment below and update the code to test the property duplicateRecordId
      //var instance = new VeevaVaultApiV251.VobjectsObjectNameActionsMergePostRequestInner();
      //expect(instance).to.be();
    });

    it('should have the property mainRecordId (base name: "main_record_id")', function() {
      // uncomment below and update the code to test the property mainRecordId
      //var instance = new VeevaVaultApiV251.VobjectsObjectNameActionsMergePostRequestInner();
      //expect(instance).to.be();
    });

  });

}));
