<?php
/**
 * VobjectsObjectNameActionsMergePostRequestInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Veeva Vault API v25.1
 *
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * VobjectsObjectNameActionsMergePostRequestInnerTest Class Doc Comment
 *
 * @category    Class
 * @description VobjectsObjectNameActionsMergePostRequestInner
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VobjectsObjectNameActionsMergePostRequestInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VobjectsObjectNameActionsMergePostRequestInner"
     */
    public function testVobjectsObjectNameActionsMergePostRequestInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "duplicate_record_id"
     */
    public function testPropertyDuplicateRecordId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "main_record_id"
     */
    public function testPropertyMainRecordId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
