/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class VobjectsObjectNameActionsMergePostRequestInner {
  
  @SerializedName("duplicate_record_id")
  private String duplicateRecordId = null;
  @SerializedName("main_record_id")
  private String mainRecordId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDuplicateRecordId() {
    return duplicateRecordId;
  }
  public void setDuplicateRecordId(String duplicateRecordId) {
    this.duplicateRecordId = duplicateRecordId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMainRecordId() {
    return mainRecordId;
  }
  public void setMainRecordId(String mainRecordId) {
    this.mainRecordId = mainRecordId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VobjectsObjectNameActionsMergePostRequestInner vobjectsObjectNameActionsMergePostRequestInner = (VobjectsObjectNameActionsMergePostRequestInner) o;
    return (this.duplicateRecordId == null ? vobjectsObjectNameActionsMergePostRequestInner.duplicateRecordId == null : this.duplicateRecordId.equals(vobjectsObjectNameActionsMergePostRequestInner.duplicateRecordId)) &&
        (this.mainRecordId == null ? vobjectsObjectNameActionsMergePostRequestInner.mainRecordId == null : this.mainRecordId.equals(vobjectsObjectNameActionsMergePostRequestInner.mainRecordId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.duplicateRecordId == null ? 0: this.duplicateRecordId.hashCode());
    result = 31 * result + (this.mainRecordId == null ? 0: this.mainRecordId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class VobjectsObjectNameActionsMergePostRequestInner {\n");
    
    sb.append("  duplicateRecordId: ").append(duplicateRecordId).append("\n");
    sb.append("  mainRecordId: ").append(mainRecordId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
