/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;




public class VobjectsObjectNameActionsMergePostRequestInner  {
  
  private String duplicateRecordId;

  private String mainRecordId;

 /**
   * Get duplicateRecordId
   * @return duplicateRecordId
  **/
  public String getDuplicateRecordId() {
    return duplicateRecordId;
  }

  /**
    * Set duplicateRecordId
  **/
  public void setDuplicateRecordId(String duplicateRecordId) {
    this.duplicateRecordId = duplicateRecordId;
  }

  public VobjectsObjectNameActionsMergePostRequestInner duplicateRecordId(String duplicateRecordId) {
    this.duplicateRecordId = duplicateRecordId;
    return this;
  }

 /**
   * Get mainRecordId
   * @return mainRecordId
  **/
  public String getMainRecordId() {
    return mainRecordId;
  }

  /**
    * Set mainRecordId
  **/
  public void setMainRecordId(String mainRecordId) {
    this.mainRecordId = mainRecordId;
  }

  public VobjectsObjectNameActionsMergePostRequestInner mainRecordId(String mainRecordId) {
    this.mainRecordId = mainRecordId;
    return this;
  }


  /**
    * Create a string representation of this pojo.
  **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VobjectsObjectNameActionsMergePostRequestInner {\n");
    
    sb.append("    duplicateRecordId: ").append(toIndentedString(duplicateRecordId)).append("\n");
    sb.append("    mainRecordId: ").append(toIndentedString(mainRecordId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

