/*
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * VobjectsObjectNameActionsMergePostRequestInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-11T22:20:50.110613320Z[Etc/UTC]", comments = "Generator version: 7.14.0")
public class VobjectsObjectNameActionsMergePostRequestInner {
  public static final String SERIALIZED_NAME_DUPLICATE_RECORD_ID = "duplicate_record_id";
  @SerializedName(SERIALIZED_NAME_DUPLICATE_RECORD_ID)
  @javax.annotation.Nullable
  private String duplicateRecordId;

  public static final String SERIALIZED_NAME_MAIN_RECORD_ID = "main_record_id";
  @SerializedName(SERIALIZED_NAME_MAIN_RECORD_ID)
  @javax.annotation.Nullable
  private String mainRecordId;

  public VobjectsObjectNameActionsMergePostRequestInner() {
  }

  public VobjectsObjectNameActionsMergePostRequestInner duplicateRecordId(@javax.annotation.Nullable String duplicateRecordId) {
    this.duplicateRecordId = duplicateRecordId;
    return this;
  }

  /**
   * Get duplicateRecordId
   * @return duplicateRecordId
   */
  @javax.annotation.Nullable
  public String getDuplicateRecordId() {
    return duplicateRecordId;
  }

  public void setDuplicateRecordId(@javax.annotation.Nullable String duplicateRecordId) {
    this.duplicateRecordId = duplicateRecordId;
  }


  public VobjectsObjectNameActionsMergePostRequestInner mainRecordId(@javax.annotation.Nullable String mainRecordId) {
    this.mainRecordId = mainRecordId;
    return this;
  }

  /**
   * Get mainRecordId
   * @return mainRecordId
   */
  @javax.annotation.Nullable
  public String getMainRecordId() {
    return mainRecordId;
  }

  public void setMainRecordId(@javax.annotation.Nullable String mainRecordId) {
    this.mainRecordId = mainRecordId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VobjectsObjectNameActionsMergePostRequestInner vobjectsObjectNameActionsMergePostRequestInner = (VobjectsObjectNameActionsMergePostRequestInner) o;
    return Objects.equals(this.duplicateRecordId, vobjectsObjectNameActionsMergePostRequestInner.duplicateRecordId) &&
        Objects.equals(this.mainRecordId, vobjectsObjectNameActionsMergePostRequestInner.mainRecordId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(duplicateRecordId, mainRecordId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VobjectsObjectNameActionsMergePostRequestInner {\n");
    sb.append("    duplicateRecordId: ").append(toIndentedString(duplicateRecordId)).append("\n");
    sb.append("    mainRecordId: ").append(toIndentedString(mainRecordId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("duplicate_record_id", "main_record_id"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to VobjectsObjectNameActionsMergePostRequestInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VobjectsObjectNameActionsMergePostRequestInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VobjectsObjectNameActionsMergePostRequestInner is not found in the empty JSON string", VobjectsObjectNameActionsMergePostRequestInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VobjectsObjectNameActionsMergePostRequestInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VobjectsObjectNameActionsMergePostRequestInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("duplicate_record_id") != null && !jsonObj.get("duplicate_record_id").isJsonNull()) && !jsonObj.get("duplicate_record_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `duplicate_record_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("duplicate_record_id").toString()));
      }
      if ((jsonObj.get("main_record_id") != null && !jsonObj.get("main_record_id").isJsonNull()) && !jsonObj.get("main_record_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `main_record_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("main_record_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VobjectsObjectNameActionsMergePostRequestInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VobjectsObjectNameActionsMergePostRequestInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VobjectsObjectNameActionsMergePostRequestInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VobjectsObjectNameActionsMergePostRequestInner.class));

       return (TypeAdapter<T>) new TypeAdapter<VobjectsObjectNameActionsMergePostRequestInner>() {
           @Override
           public void write(JsonWriter out, VobjectsObjectNameActionsMergePostRequestInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VobjectsObjectNameActionsMergePostRequestInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of VobjectsObjectNameActionsMergePostRequestInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of VobjectsObjectNameActionsMergePostRequestInner
   * @throws IOException if the JSON string is invalid with respect to VobjectsObjectNameActionsMergePostRequestInner
   */
  public static VobjectsObjectNameActionsMergePostRequestInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VobjectsObjectNameActionsMergePostRequestInner.class);
  }

  /**
   * Convert an instance of VobjectsObjectNameActionsMergePostRequestInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

