# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""_vobjects__object_name__actions_merge_post_request_inner

    VobjectsObjectNameActionsMergePostRequestInner(;
        duplicate_record_id=nothing,
        main_record_id=nothing,
    )

    - duplicate_record_id::String
    - main_record_id::String
"""
Base.@kwdef mutable struct VobjectsObjectNameActionsMergePostRequestInner <: OpenAPI.APIModel
    duplicate_record_id::Union{Nothing, String} = nothing
    main_record_id::Union{Nothing, String} = nothing

    function VobjectsObjectNameActionsMergePostRequestInner(duplicate_record_id, main_record_id, )
        o = new(duplicate_record_id, main_record_id, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type VobjectsObjectNameActionsMergePostRequestInner

const _property_types_VobjectsObjectNameActionsMergePostRequestInner = Dict{Symbol,String}(Symbol("duplicate_record_id")=>"String", Symbol("main_record_id")=>"String", )
OpenAPI.property_type(::Type{ VobjectsObjectNameActionsMergePostRequestInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_VobjectsObjectNameActionsMergePostRequestInner[name]))}

function OpenAPI.check_required(o::VobjectsObjectNameActionsMergePostRequestInner)
    true
end

function OpenAPI.validate_properties(o::VobjectsObjectNameActionsMergePostRequestInner)
    OpenAPI.validate_property(VobjectsObjectNameActionsMergePostRequestInner, Symbol("duplicate_record_id"), o.duplicate_record_id)
    OpenAPI.validate_property(VobjectsObjectNameActionsMergePostRequestInner, Symbol("main_record_id"), o.main_record_id)
end

function OpenAPI.validate_property(::Type{ VobjectsObjectNameActionsMergePostRequestInner }, name::Symbol, val)


end
