// tslint:disable
/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VobjectsObjectNameActionsMergePostRequestInner
 */
export interface VobjectsObjectNameActionsMergePostRequestInner  {
    /**
     * 
     * @type {string}
     * @memberof VobjectsObjectNameActionsMergePostRequestInner
     */
    duplicateRecordId?: string;
    /**
     * 
     * @type {string}
     * @memberof VobjectsObjectNameActionsMergePostRequestInner
     */
    mainRecordId?: string;
}

export function VobjectsObjectNameActionsMergePostRequestInnerFromJSON(json: any): VobjectsObjectNameActionsMergePostRequestInner {
    return {
        'duplicateRecordId': !exists(json, 'duplicate_record_id') ? undefined : json['duplicate_record_id'],
        'mainRecordId': !exists(json, 'main_record_id') ? undefined : json['main_record_id'],
    };
}

export function VobjectsObjectNameActionsMergePostRequestInnerToJSON(value?: VobjectsObjectNameActionsMergePostRequestInner): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'duplicate_record_id': value.duplicateRecordId,
        'main_record_id': value.mainRecordId,
    };
}


