# #Veeva Vault API v25.1
#
##The latest GA version of the Vault REST API.
#
#The version of the OpenAPI document: 1.0.0
#
#Generated by: https://openapi-generator.tech
#Generator version: 7.14.0
#

# Dependencies
require "crest"
require "log"

module OpenAPIClient
  Log = ::Log.for("OpenAPIClient") # => Log for OpenAPIClient source

  VERSION = {{ `shards version #{__DIR__}`.chomp.stringify }}

  # Return the default `Configuration` object.
  def self.configure
    Configuration.default
  end

  # Customize default settings for the SDK using block.
  #
  # ```
  # OpenAPIClient.configure do |config|
  #   config.username = "xxx"
  #   config.password = "xxx"
  # end
  # ```
  def self.configure
    yield Configuration.default
  end
end

require "./openapi_client/**"
