--[[
  Veeva Vault API v25.1

  The latest GA version of the Vault REST API.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- _vobjects__object_name__actions_merge_post_request_inner class
local _vobjects__object_name__actions_merge_post_request_inner = {}
local _vobjects__object_name__actions_merge_post_request_inner_mt = {
	__name = "_vobjects__object_name__actions_merge_post_request_inner";
	__index = _vobjects__object_name__actions_merge_post_request_inner;
}

local function cast__vobjects__object_name__actions_merge_post_request_inner(t)
	return setmetatable(t, _vobjects__object_name__actions_merge_post_request_inner_mt)
end

local function new__vobjects__object_name__actions_merge_post_request_inner(duplicate_record_id, main_record_id)
	return cast__vobjects__object_name__actions_merge_post_request_inner({
		["duplicate_record_id"] = duplicate_record_id;
		["main_record_id"] = main_record_id;
	})
end

return {
	cast = cast__vobjects__object_name__actions_merge_post_request_inner;
	new = new__vobjects__object_name__actions_merge_post_request_inner;
}
