/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VobjectsObjectNameActionsMergePostRequestInner model module.
 * @module model/VobjectsObjectNameActionsMergePostRequestInner
 * @version 1.0.0
 */
class VobjectsObjectNameActionsMergePostRequestInner {
    /**
     * @member {String} duplicate_record_id
     * @type {String}
     */
    duplicate_record_id;
    /**
     * @member {String} main_record_id
     * @type {String}
     */
    main_record_id;

    

    /**
     * Constructs a new <code>VobjectsObjectNameActionsMergePostRequestInner</code>.
     * @alias module:model/VobjectsObjectNameActionsMergePostRequestInner
     */
    constructor() { 
        
        VobjectsObjectNameActionsMergePostRequestInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VobjectsObjectNameActionsMergePostRequestInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VobjectsObjectNameActionsMergePostRequestInner} obj Optional instance to populate.
     * @return {module:model/VobjectsObjectNameActionsMergePostRequestInner} The populated <code>VobjectsObjectNameActionsMergePostRequestInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VobjectsObjectNameActionsMergePostRequestInner();

            if (data.hasOwnProperty('duplicate_record_id')) {
                obj['duplicate_record_id'] = ApiClient.convertToType(data['duplicate_record_id'], 'String');
            }
            if (data.hasOwnProperty('main_record_id')) {
                obj['main_record_id'] = ApiClient.convertToType(data['main_record_id'], 'String');
            }
        }
        return obj;
    }
}



export default VobjectsObjectNameActionsMergePostRequestInner;

