/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

import org.junit.jupiter.api.Test;

/**
 * Model tests for VobjectsObjectNameActionsMergePostRequestInner
 */
public class VobjectsObjectNameActionsMergePostRequestInnerTest {
    private final VobjectsObjectNameActionsMergePostRequestInner model = new VobjectsObjectNameActionsMergePostRequestInner();

    /**
     * Model tests for VobjectsObjectNameActionsMergePostRequestInner
     */
    @Test
    public void testVobjectsObjectNameActionsMergePostRequestInner() {
        // TODO: test VobjectsObjectNameActionsMergePostRequestInner
    }

    /**
     * Test the property 'duplicateRecordId'
     */
    @Test
    public void duplicateRecordIdTest() {
        // TODO: test duplicateRecordId
    }

    /**
     * Test the property 'mainRecordId'
     */
    @Test
    public void mainRecordIdTest() {
        // TODO: test mainRecordId
    }

}
