/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import VobjectsObjectNameActionsMergePostRequestInner from './model/VobjectsObjectNameActionsMergePostRequestInner';
import DefaultApi from './api/DefaultApi';


/**
* The latest GA version of the Vault REST API..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var VeevaVaultApiV251 = require('index'); // See note below*.
* var xxxSvc = new VeevaVaultApiV251.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new VeevaVaultApiV251.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new VeevaVaultApiV251.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new VeevaVaultApiV251.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The VobjectsObjectNameActionsMergePostRequestInner model constructor.
     * @property {module:model/VobjectsObjectNameActionsMergePostRequestInner}
     */
    VobjectsObjectNameActionsMergePostRequestInner,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
