name: Generate & publish API docs

on:
  workflow_run:
    workflows: ["Validate OpenAPI spec"]
    types: [completed]
  workflow_dispatch: {}

jobs:
  build-docs:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      # checkout the exact commit validated in the previous workflow
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - uses: actions/setup-node@v4
      - name: Bundle ReDoc HTML
        run: |
          # use latest available redoc-cli version
          npx --yes redoc-cli@0.13.21 bundle spec/openapi.yaml -o site/index.html

      # ── update generated-docs branch ──────────────────────────
      - name: Commit docs to generated-docs
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name  "github-actions[bot]"
          git fetch origin
          git checkout -B generated-docs
          git rm -rf . >/dev/null 2>&1 || true
          cp -r site/* .
          git add .
          git commit -m "docs: regenerate from ${GITHUB_SHA}" || echo "No changes"
          git push --force origin generated-docs

      # ── deploy GitHub Pages ──────────────────────────────────
      - uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: site
      - uses: actions/deploy-pages@v4
