/**
 * Veeva Vault API v25.1
 * The latest GA version of the Vault REST API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class VobjectsObjectNameActionsMergePostRequestInner {
    'duplicateRecordId'?: string;
    'mainRecordId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "duplicateRecordId",
            "baseName": "duplicate_record_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "mainRecordId",
            "baseName": "main_record_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VobjectsObjectNameActionsMergePostRequestInner.attributeTypeMap;
    }

    public constructor() {
    }
}
