/*
 * Veeva Vault API v25.1
 *
 * The latest GA version of the Vault REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing VobjectsObjectNameActionsMergePostRequestInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VobjectsObjectNameActionsMergePostRequestInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VobjectsObjectNameActionsMergePostRequestInner
        //private VobjectsObjectNameActionsMergePostRequestInner instance;

        public VobjectsObjectNameActionsMergePostRequestInnerTests()
        {
            // TODO uncomment below to create an instance of VobjectsObjectNameActionsMergePostRequestInner
            //instance = new VobjectsObjectNameActionsMergePostRequestInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VobjectsObjectNameActionsMergePostRequestInner
        /// </summary>
        [Fact]
        public void VobjectsObjectNameActionsMergePostRequestInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" VobjectsObjectNameActionsMergePostRequestInner
            //Assert.IsType<VobjectsObjectNameActionsMergePostRequestInner>(instance);
        }

        /// <summary>
        /// Test the property 'DuplicateRecordId'
        /// </summary>
        [Fact]
        public void DuplicateRecordIdTest()
        {
            // TODO unit test for the property 'DuplicateRecordId'
        }

        /// <summary>
        /// Test the property 'MainRecordId'
        /// </summary>
        [Fact]
        public void MainRecordIdTest()
        {
            // TODO unit test for the property 'MainRecordId'
        }
    }
}
